### ISSUE TITLE
e-hentai UI溢出

### ISSUE THREAD

**Issue by fireattack** [hymbz/ComicReadScript#10]
![image](https://user-images.githubusercontent.com/4130991/50739665-1ae6f680-11a9-11e9-8e1f-bd13820c8cd0.png)

https://e-hentai.org/g/1342223/d2617cd9f5/

另外，那个”ehentai、nhentai 加载过程中可以点击按钮，不等待全部图片加载完毕就直接进入阅读模式。“的功能能否也支持下exhentai？~~我这里测试e-hentai有效，但是exhentai无效。~~ e-hentai也经常失效……

多谢了

**Comment by hymbz** [comment]
回复晚了抱歉。直接进入阅读模式那个功能失效具体是怎样？脚本需要先开始加载图片，等所有图片都开始加载后点击才会有反应。另外关于 UI 溢出，是因为你开启了「multi-page viewer」功能的原因，把位置给占了。。。我有空的时候再改改吧。

**Comment by fireattack** [comment]
“直接进入阅读模式那个功能失效”的问题我单独开了个ticket描述，不过现在遇到的是nhentai
