### ISSUE TITLE
v7.1.1在exhentai报错

### ISSUE THREAD

**Issue by LitCcc** [hymbz/ComicReadScript#100]
点击 Load comic 后加载到第9页报错，右下角提示 Cannot read properties of undefined (reading 'some')

**Comment by hymbz** [comment]
漫画地址发下

**Comment by LitCcc** [comment]
似乎任何一个都会报错，对比之后发现只有chrome有这个问题，edge和firefox正常，已经禁用了其他扩展和脚本，只保留Tampermonkey和ComicReadScript

**Comment by hymbz** [comment]
我这边是三个浏览器都没问题。

感觉可能是配置问题，在 Tampermonkey 里点进脚本，切换到`存储`标签可以看到脚本的配置（如果没有`存储`标签要去设置里把配置模式设为高级），把你的配置发给我看下。

**Comment by hymbz** [comment]
确实是配置的问题，我会在下个版本更新里修复这个问题。

如果你要现在就解决的话，把

```
    "ehentai": {
        "option": {
            "translation": {
                "server": "本地部署",
                "options": {
                    "translator": "google"
                }
            }
        }
    },
```

这几行删掉就可以了。或者更简单点就是直接重装脚本，相当于清空配置。

**Comment by LitCcc** [comment]
删掉以后正常了，非常感谢！
