### ISSUE TITLE
[Feature request] Open archives from web in PWA

### ISSUE THREAD

**Issue by EnergoStalin** [hymbz/ComicReadScript#102]
Make possible dragging/pasting archive url into PWA

**Comment by hymbz** [comment]
What is archive url?

**Comment by EnergoStalin** [comment]
maybe it would be better to say support loading archives from http scheme. ie. https://somesite.com/archive.zip

**Comment by hymbz** [comment]
Good idea, I will add this feature.

**Comment by EnergoStalin** [comment]
as for use case it can be kemono party having embedded archive link or possibly to use mega links through some proxy

**Comment by hymbz** [comment]
Already updated.

In addition to entering the URL by clicking a button, you can also use `https://comic-read.pages.dev/?url=<archive url>` to quickly input the URL. I believe that this can simplify the operation by leveraging the browser's custom search function.

**Comment by EnergoStalin** [comment]
Thanks! Confirmed
