### ISSUE TITLE
关于“禁止图片自动缩放”功能

### ISSUE THREAD

**Issue by blass0009** [hymbz/ComicReadScript#106]
能不能为此功能增加一个快捷键？
或者出现在快捷键自定义栏，手动配置快捷键

此外，我注意到当图片大于浏览器分辨率时，即使关闭此功能，图片依然会缩小
所以此功能实际上是“禁止图片自动放大”而不是“缩放”
在极其少见的情况下，图片有可能只比浏览器窗口大几个像素，此时禁止图片缩小是有意义的
个人觉得可以把这个功能拆分成2个：
“禁止图片自动放大”和“禁止图片自动缩小”

**Comment by hymbz** [comment]
其实之前确实是叫`禁止放大图片`来着，就前几天才刚改的，因为感觉会产生歧义，误以为是禁止放大模式。之后会把缩放改成放大的。

`禁止图片自动缩小`是什么效果？是类似现在的放大模式通过拖拽来移动图片吗？

小图被浏览器自动放大可能会变模糊，但大图被缩小也就会出现摩尔纹这一个问题吧，我是很少遇到这种情况，偶尔遇到也是通过调整浏览器窗口大小来减小。

能具体说说你遇到的场景吗？

**Comment by blass0009** [comment]
> 禁止图片自动缩小是什么效果？是类似现在的放大模式通过拖拽来移动图片吗？

不是，就是让图片原尺寸居中显示，多出的部分直接不显示，也没有任何办法拖拽或者移动图片。就是真正的不显示。

在极其罕见的情况下，图片可能仅比浏览器窗口大几个像素。我认为此时相比于对图片进行缩小处理，直接显示原图，抛弃超出浏览器窗口的像素，避免对图片处理，对于保持图像清晰度是有意义的。尤其是相比图像而言，字体受影响程度比较大，会变得比较“虚”。

附图左边是原始图片，右边是被稍微缩小了一点点的图片。
![c](https://github.com/hymbz/ComicReadScript/assets/20455106/949bb889-9309-477d-a52f-00a636527ac3)

**Comment by hymbz** [comment]
感觉出现几率太低，实现起来也有点麻烦，经过考虑还是决定不加这个功能，抱歉了。

另外脚本已经更新加上了切换快捷键的选项，因为感觉使用场景比较少所以没有设默认按键。功能名字也改了。
