### ISSUE TITLE
请求适配colamanga

### ISSUE THREAD

**Issue by MrPinku** [hymbz/ComicReadScript#109]
https://www.colamanga.com/
这里看漫画需要手动滚动才会加载图片（并不是翻页），但是用东方翻页机这网站会提示检测到违规行为会封ip所以不能用东方翻页机之类的脚本。不过问题不大，以前我都是用可以靠手动拉到底等加载完毕后用简易模式。
但是现在不行，每次加载完以后进简易模式里面都是空白图
![image](https://github.com/hymbz/ComicReadScript/assets/79267206/1940853b-4f95-48d8-9474-eaa5a8393ef5)
![image](https://github.com/hymbz/ComicReadScript/assets/79267206/3a414679-8e88-4fd8-a442-97ecb533e867)
图片已经加载完但是悬浮按钮显示0/30。
求大大支招或者适配一下谢谢！

**Comment by hymbz** [comment]
已更新加强了简易模式，现在可以正常加载了。

**Comment by MrPinku** [comment]
刚刚试了下还是不行……

**Comment by MrPinku** [comment]
> 已更新加强了简易模式，现在可以正常加载了。

刚刚试了下还是不行……

**Comment by hymbz** [comment]
网址发下我看看，我这边是没问题

**Comment by MrPinku** [comment]
https://www.colamanga.com/manga-kx05635/1/92.html

**Comment by hymbz** [comment]
没想到不同漫画的反爬机制还不一样。。我再研究下

我是用 <https://www.colamanga.com/manga-za76213/1/5.html> 来测试的，这个你那边能正常加载吗？

**Comment by MrPinku** [comment]
这个可以正常加载

**Comment by MrPinku** [comment]
另外简易模式好像不能保存黑夜模式设置？

**Comment by MrPinku** [comment]
> 另外简易模式好像不能保存黑夜模式设置？

不好意思没事了，可以保存orz

**Comment by hymbz** [comment]
更新了，你再试试

**Comment by MrPinku** [comment]
刚试过能用了！而且可以自动加载后面的图片了~
