### ISSUE TITLE
在 dm5.com 下載後，zip 內檔案的副檔名後面多出一堆字串

### ISSUE THREAD

**Issue by frank-h** [hymbz/ComicReadScript#110]
像這樣：
`01.jpg?cid=1407303&key=5b339fc8c19da9fd7d9dffe29f16c7b3&uk=707970C804232C2908923C36C437DBA3FCE1636B48C841AE7CF5C076E0D74646&hkey=237e94cd48f5a536df3906aadca9d9e0bf4f71bf&t=1696348800`

**Comment by hymbz** [comment]
已更新修复
