### ISSUE TITLE
[Bug]: PWA "Comic Read not istalled" error when using ?url=<archive url>

### ISSUE THREAD

**Issue by EnergoStalin** [hymbz/ComicReadScript#113]
If i understand correctly from what you [said](https://github.com/hymbz/ComicReadScript/issues/102#issuecomment-1742127631) when you implemented this feature. Such

`https://comic-read.pages.dev/?url=https%3A%2F%2Fc6.kemono.party%2Fdata%2F03%2F57%2F03577a30cb1b7d80bd6911021e7e33cfd2a6e30912585d3580d245ade0ae375a.zip` 

[link](https://comic-read.pages.dev/?url=https%3A%2F%2Fc6.kemono.party%2Fdata%2F03%2F57%2F03577a30cb1b7d80bd6911021e7e33cfd2a6e30912585d3580d245ade0ae375a.zip) should start download immediately. Or there's a browser limitation where i should click on the page first before script being able to download? Anyway in such case error message is not helpful i think.

Sorry for didn't testing it earlier.

Here's the snippet for kemono.paty to convert all .zip links to PWA links i'm using
```js
Array.from(document.querySelectorAll("a")).filter(e => e.href.endsWith(".zip")).forEach(e => {
	e.textContent = e.textContent.replace("Download", "ComicReadPWA")
	e.removeAttribute("download")
	
	e.href = `https://comic-read.pages.dev/?url=${encodeURIComponent(e.href)}`
	e.target = "_blank"
})
```

Through "Enter URL" works as expected and setting the same link in window location

**Comment by EnergoStalin** [comment]
problem in target="_blank"

**Comment by EnergoStalin** [comment]
Script loading later than PWA performing first check when using ?url= API. If opening in current tab it's already loaded i guess so it's not a problem. Probably need some delay to let script load first in PWA.

**Comment by hymbz** [comment]
Is there any error message? I tried the link and it seems to be working fine.

You don't need to click on the page, just wait a few seconds after opening it and you will see the download button change to "downloading" style.

**Comment by EnergoStalin** [comment]
I can reproduce it opening this `https://comic-read.pages.dev/?url=https%3A%2F%2Fc6.kemono.party%2Fdata%2F03%2F57%2F03577a30cb1b7d80bd6911021e7e33cfd2a6e30912585d3580d245ade0ae375a.zip` with middle click(new tab) opening in same tab works perfect

![image](https://github.com/hymbz/ComicReadScript/assets/49844515/8c04dbdd-4498-4aad-8dae-ccf8c4c701be)

Got this in yandex(chromium) and firefox browsers

**Comment by EnergoStalin** [comment]
Maybe not perfect seems very inconsistent now it even don't work in the same tab.

**Comment by EnergoStalin** [comment]
Fresh browser profile reproducible

**Comment by hymbz** [comment]
Successfully reproduced, I will fix it later.

**Comment by hymbz** [comment]
Already updated.

**Comment by EnergoStalin** [comment]
Works perfectly now thanks!
