### ISSUE TITLE
[优化] 已经加载的图片的再下载时间有点点长的建议

### ISSUE THREAD

**Issue by zxw7606** [hymbz/ComicReadScript#116]
在简易模式下阅读 ，点击翻译的时候， 发现已经加载的图片还需要进行下载图片，然后上传翻译服务器。请问能否进行一下优化，直接获取加载图片的数据进行上传呢。类似这样的

![image](https://github.com/hymbz/ComicReadScript/assets/3738414/9916a705-2015-4f29-8417-cca0c0d69332)

**Comment by hymbz** [comment]
不直接用 canvas 获取图片是因为有些网站的图片有 CORS 限制，没办法这样转换，而且用 canvas 转出来的图片相比原图体积也会更大。目前没这么搞是因为感觉没什么必要，下载个图片也就几秒而已。能具体说下你的使用场景吗？

**Comment by zxw7606** [comment]
> 不直接用 canvas 获取图片是因为有些网站的图片有 CORS 限制，没办法这样转换，而且用 canvas 转出来的图片相比原图体积也会更大。目前没这么搞是因为感觉没什么必要，下载个图片也就几秒而已。能具体说下你的使用场景吗？

哦哦这样啊，那能否预加载(指定图片数量的)图的翻译呢， 我的使用场景是当前我看第一张图片，点翻译要等5s,看完之后看下一张，又得等5s

**Comment by zxw7606** [comment]
对了有一个BUG 就是点翻译等待的时候，然后我手机锁屏，然后解锁之后，就无法再进行翻译了，状态值就停留在锁屏前的那个时候，似乎某个变量值没有重置的样子。 导致得刷新一下页面， 然后之前翻译的图片全没了

比如锁屏前是“正在下载”， 锁屏打开之后，永远都是“正在下载”

**Comment by hymbz** [comment]
那感觉确实没必要优化，毕竟翻译时的主要耗时应该是在翻译图片上。

点完翻译按钮不用原地等着，可以直接切到下一页去再点按钮的。另外如果你使用自部署的翻译的话，在翻页设置里也有「翻译全部图片」的开关。Cotrans 只能手动指定翻译图片是为了防止把一些根本不需要翻译的图片也丢给 Cotrans 白白浪费了服务器资源。

你手机用的浏览器和油猴扩展是什么？

**Comment by zxw7606** [comment]
> 那感觉确实没必要优化，毕竟翻译时的主要耗时应该是在翻译图片上。
> 
> 点完翻译按钮不用原地等着，可以直接切到下一页去再点按钮的。另外如果你使用自部署的翻译的话，在翻页设置里也有「翻译全部图片」的开关。Cotrans 只能手动指定翻译图片是为了防止把一些根本不需要翻译的图片也丢给 Cotrans 白白浪费了服务器资源。
> 
> 你手机用的浏览器和油猴扩展是什么？

主要「翻译全部图片」有个不好的点就是刷新一下页面就得从头再翻译， 那能否加个从当前浏览位置全部翻译呢？

手机是安卓 KiWi 浏览器 + Tampermonkey

**Comment by hymbz** [comment]
> 主要「翻译全部图片」有个不好的点就是刷新一下页面就得从头再翻译， 那能否加个从当前浏览位置全部翻译呢？
> 
> 手机是安卓 KiWi 浏览器 + Tampermonkey

这个没问题，下次更新加上。

**Comment by hymbz** [comment]
> 对了有一个BUG 就是点翻译等待的时候，然后我手机锁屏，然后解锁之后，就无法再进行翻译了，状态值就停留在锁屏前的那个时候，似乎某个变量值没有重置的样子。 导致得刷新一下页面， 然后之前翻译的图片全没了
> 
> 比如锁屏前是“正在下载”， 锁屏打开之后，永远都是“正在下载”

问下是在哪个网站上翻译的？我这边试了几个都无法复现。

**Comment by zxw7606** [comment]
> > 对了有一个BUG 就是点翻译等待的时候，然后我手机锁屏，然后解锁之后，就无法再进行翻译了，状态值就停留在锁屏前的那个时候，似乎某个变量值没有重置的样子。 导致得刷新一下页面， 然后之前翻译的图片全没了
> > 比如锁屏前是“正在下载”， 锁屏打开之后，永远都是“正在下载”
> 
> 问下是在哪个网站上翻译的？我这边试了几个都无法复现。

不好意思没看到， 在[https://comick.app/](https://comick.app/), 试了一下最新的没问题了
