### ISSUE TITLE
[feature request] 导出浏览历史记录

### ISSUE THREAD

**Issue by ZeppLu** [hymbz/ComicReadScript#12]
如题，导出订阅的功能很好用，但有很多时候会用浏览历史而非订阅做标记，所以希望能添加这个功能

**Comment by hymbz** [comment]
用浏览历史做标记。。还有这招啊。但动漫之家云端只能存50条记录，你只需要导出这50条记录吗？还是需要像动漫之家安卓端那样增加一个本机记录功能来记录和导出浏览历史

**Comment by ZeppLu** [comment]
看了一下，好像确实只有五十条，不过对于一般的非重度漫画患者应该也勉强够了（我的云端历史已经覆盖了最近四个月的记录）。本机记录功能的话，我个人虽然用不上，但觉得会挺有用的。

**Comment by hymbz** [comment]
已更新云端导出功能，本机记录功能既然用处不大的话就先不做了
