### ISSUE TITLE
如果能有安卓端就好了

### ISSUE THREAD

**Issue by Aisakaguya** [hymbz/ComicReadScript#121]
作者的阅读器太棒了，要是有安卓端就好了，这样就可以在手机上阅读本地漫画了

**Comment by hymbz** [comment]
😂安卓上的漫画阅读APP太卷了，感觉没必要重复造轮子，目前也没有学安卓的打算。

不过目前还是可以在手机上用 PWA 版来看本地漫画的，就是现在没办法选择整个文件夹，只能手动一个文件一个文件的选中，这也只能等之后相关 API 适配了。

**Comment by SaltedFish-Extreme** [comment]
我用的安卓平板，装的可以使用油猴插件的狐猴浏览器和kiwi浏览器，可以使用油猴插件和其他的浏览器插件，很方便

![微信图片_20240116110236](https://github.com/hymbz/ComicReadScript/assets/54784104/0ea99cc6-898a-45b3-a35c-0c536ae518cd)
![微信图片_20240116110242](https://github.com/hymbz/ComicReadScript/assets/54784104/d01fae30-b278-47ab-a2af-8c65b6b2c2cb)
