### ISSUE TITLE
求适配Nyahantai

### ISSUE THREAD

**Issue by eastlovsky** [hymbz/ComicReadScript#123]
https://nyahentai.red/

**Comment by hymbz** [comment]
看着和 nhentai 一模一样啊，两者有什么区别吗？

**Comment by hymbz** [comment]
在吗？如果只是 nhentai 的镜像站的话，那没什么必要适配吧，直接上 nhentai 不就好了？

另外我用`nyahentai`和`喵绅士`作为关键词进行搜索，找出了一堆网址，并且上面的资源也是不同的。我之前从来没上过这个网站，你能再多介绍下吗？

**Comment by hymbz** [comment]
太久没回我先关了哈
