### ISSUE TITLE
在按照本地部署流程时遇到的问题

### ISSUE THREAD

**Issue by tgchara** [hymbz/ComicReadScript#124]
![docker-compose](https://github.com/hymbz/ComicReadScript/assets/152972141/286a0afd-8697-4267-bf13-94c6067e0b7c)
到这一步，在搜索引擎找的解决方案都是释放磁盘空间，但没发现占用多少，单凭我个人找不到什么办法了
![docker](https://github.com/hymbz/ComicReadScript/assets/152972141/91c9cc9b-9f51-4e3e-8187-6a09a43602c4)

**Comment by hymbz** [comment]
首先建议去 [manga-image-translator](https://github.com/zyddnys/manga-image-translator/issues) 那提 issues，因为其相关东西其实我也不熟（

不过看截图，上面截图是在 windows D盘下一个文件夹执行了 `docker-compose up`，但下面截图却是展示的一个 linux 虚拟机内的硬盘信息？单看上面截图不是该检查D盘空间吗？~~（不过我没用过这个虚拟机也懒得去查了，不是这个问题的话当我没说。~~

除此以外可能就是虚拟机本身的问题了吧，试试换个虚拟机？

**Comment by tgchara** [comment]
因为报错那会用的是docker toolbox，自己对这方面也不熟悉，找了各种处理方法都没成功

后来重新下了个docker desktop，不清楚啥原因反正是没有再报错了
