### ISSUE TITLE
加载脚本依赖发生错误

### ISSUE THREAD

**Issue by tafeilgh** [hymbz/ComicReadScript#131]
你好,更新到ComicRead, 8.2.11时显示加载脚本依赖发生错误。使用的是暴力猴
![加载脚本依赖发生错误](https://github.com/hymbz/ComicReadScript/assets/100503528/c622a358-d844-4676-8baf-c8d162daef30)

**Comment by hymbz** [comment]
已更新修复。

没想到 unpkg 也会被墙，现在换成淘宝的 npmmirror 了。
