### ISSUE TITLE
似乎在ehentai会卡顿

### ISSUE THREAD

**Issue by Chunbear** [hymbz/ComicReadScript#134]
尤其是画廊页数过多的时候

**Comment by hymbz** [comment]
能再具体讲讲吗？是阅读模式卡还是网页滚动都卡？具体会持续多久？

**Comment by Chunbear** [comment]
切换为阅读模式的时候会卡顿，具体表现在加载过多图片时，用鼠标点击右侧滚动条，整个页面都会卡住
![image](https://github.com/hymbz/ComicReadScript/assets/34836688/f48fec32-355f-4106-8b23-e2eed0e49bcf)
然后页面就崩溃了。

**Comment by Chunbear** [comment]
即使点击的时候不卡，拖动几次也会卡住

**Comment by hymbz** [comment]
试了下我这边无法复现。。只能再多问问你了

1. 拖动是说拖动滚动条，还是说拖拽页面来翻页？
1. 使用滚轮或方向键来翻页会卡住吗？
1. 卡住的时候滚动条上有`淡黄色`的色块吗？
1. 等到图片都加载完毕，滚动条上没有`淡黄色`和`深灰色`的色块后再点击滚动条，还会卡住吗？

**Comment by hymbz** [comment]
另外为了保险起见，你发几个会导致卡住的画廊链接让我再试试吧

**Comment by Chunbear** [comment]
我录制了一份视频
https://wormhole.app/Ja1qX#5VD2v6lZkkp1UIM6J7wIdA
目前来看数量较多的画廊都会发生此类情况，以及这是故障发生时的进程管理器截图
![N3`P4V`MI I3F我录制了一份视频
https://wormhole.app/Ja1qX#5VD2v6lZkkp1UIM6J7wIdA
目前来看数量较多的画廊都会发生此类情况，以及这是故障发生时的进程管理器截图
N7KU8414](https://github.com/hymbz/ComicReadScript/assets/34836688/35c293be-5ca4-45a9-8a87-5d89d2412dda)

**Comment by Chunbear** [comment]
> 试了下我这边无法复现。。只能再多问问你了
> 
> 1. 拖动是说拖动滚动条，还是说拖拽页面来翻页？
> 2. 使用滚轮或方向键来翻页会卡住吗？
> 3. 卡住的时候滚动条上有`淡黄色`的色块吗？
> 4. 等到图片都加载完毕，滚动条上没有`淡黄色`和`深灰色`的色块后再点击滚动条，还会卡住吗？

拖动滚动条会卡死；没有尝试；有淡黄色色块；仅测试了淡黄条消失后，依然会卡顿

**Comment by hymbz** [comment]
确实是性能问题，在动态加载页数过多时就会触发。已更新修复。
