### ISSUE TITLE
iPad mini6上运行无反应

### ISSUE THREAD

**Issue by gofreeing** [hymbz/ComicReadScript#136]
![IMG_0003](https://github.com/hymbz/ComicReadScript/assets/56500905/f5a3e1ec-d5ec-45ea-9f8b-f819db15c609)

**Comment by hymbz** [comment]
这个油猴扩展是 Stay？Stay 没有实现 `GM_addElement` 这个 api，只能换用其他的扩展比如 Tampermonkey。

**Comment by gofreeing** [comment]
> 这个油猴扩展是 Stay？Stay 没有实现 `GM_addElement` 这个 api，只能换用其他的扩展比如 Tampermonkey。

Tampermonkey平板上下不到，有什么替代方法吗

**Comment by hymbz** [comment]
<https://www.tampermonkey.net/index.php?browser=safari&locale=zh> Tampermonkey 官网这个链接不能下吗？

**Comment by gofreeing** [comment]
> https://www.tampermonkey.net/index.php?browser=safari&locale=zh Tampermonkey 官网这个链接不能下吗？

![image](https://github.com/hymbz/ComicReadScript/assets/56500905/e3893f2e-2bce-48fd-b6e8-0648d93bcd98)
这是电脑的，我的是平板

**Comment by hymbz** [comment]
我用的安卓所以还真没注意到😂（

脚本已更新，你试下现在可以了吗？

**Comment by gofreeing** [comment]
> 我用的安卓所以还真没注意到😂（
> 
> 脚本已更新，你试下现在可以了吗？

还是没效果，和第一张图一样

**Comment by hymbz** [comment]
已更新。

借了台 iphone 来测试，这回总该没问题了。

**Comment by gofreeing** [comment]
> 已更新。
> 
> 借了台 iphone 来测试，这回总该没问题了。

好了，谢谢大佬

**Comment by alem0n** [comment]
> > 已更新。
> > 借了台 iphone 来测试，这回总该没问题了。
> 
> 好了，谢谢大佬

请问你用的哪个应用安装的脚本，我的iPad Air3也不能正常用

**Comment by gofreeing** [comment]
> > > 已更新。
> > > 借了台 iphone 来测试，这回总该没问题了。
> > 
> > 
> > 好了，谢谢大佬
> 
> 请问你用的哪个应用安装的脚本，我的iPad Air3也不能正常用

stay

**Comment by alem0n** [comment]
> > > > 已更新。
> > > > 借了台 iphone 来测试，这回总该没问题了。
> > > 
> > > 
> > > 好了，谢谢大佬
> > 
> > 
> > 请问你用的哪个应用安装的脚本，我的iPad Air3也不能正常用
> 
> stay

可以详细说一下吗，我也用的stay但是没反应。能截图看看吗

**Comment by alem0n** [comment]
> > > > > 已更新。
> > > > > 借了台 iphone 来测试，这回总该没问题了。
> > > > 
> > > > 
> > > > 好了，谢谢大佬
> > > 
> > > 
> > > 请问你用的哪个应用安装的脚本，我的iPad Air3也不能正常用
> > 
> > 
> > stay
> 
> 可以详细说一下吗，我也用的stay但是没反应。能截图看看吗

已解决。将ipad升级到iPadOS17.3就可以正常使用了
