### ISSUE TITLE
老哥，狗狗漫画网站使用这个插件，会自动翻很多页

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [hymbz/ComicReadScript#137]
[漫画连接](https://m.gougoumh.com/manhua/shoulongrenlagena/1949340.html)

![image](https://github.com/hymbz/ComicReadScript/assets/54784104/f5a34804-fcf8-43f2-938a-ad04b6b7a811)

**Comment by SaltedFish-Extreme** [comment]
我测过好几个网站，就这个网站有问题，不知道为什么，自动翻了很多页，然后还不能往前翻，将这页固定成第一页了，不过这个插件还是很方便的，跟uwp版的B站漫画一样的体验😋

**Comment by SaltedFish-Extreme** [comment]
哦，还有edge浏览器使用谷歌搜索时，开着这个油猴脚本也会出问题，搜索的页面会一直上下移动加载，不知道什么问题😂

**Comment by SaltedFish-Extreme** [comment]
录了个视频，压缩后有点糊，可以看下😂

https://github.com/hymbz/ComicReadScript/assets/54784104/8f3f9ce0-5fa6-4b33-9818-ad9fc95884e9

**Comment by hymbz** [comment]
> 哦，还有edge浏览器使用谷歌搜索时，开着这个油猴脚本也会出问题，搜索的页面会一直上下移动加载，不知道什么问题😂

是因为开启了简易阅读模式，在右下角把`记住当前站点`关掉就好

**Comment by SaltedFish-Extreme** [comment]
> 是因为开启了简易阅读模式，在右下角把`记住当前站点`关掉就好

好的，麻烦老哥看下狗狗漫画适配的问题的😂我感觉好像是页数过多，只取了中间的加载出来了，开始的几页和最后几页都没加载到😂

**Comment by hymbz** [comment]
已更新修复。

是因为网站的懒加载机制导致的，头一次见到加载完图片还会先隐藏起来等滚到再渲染的，因为没考虑到这种情况导致脚本判断出了错。

**Comment by SaltedFish-Extreme** [comment]
好的，麻烦老哥了😘
