### ISSUE TITLE
使用翻译的自定义url时显示"找不到服务器"

### ISSUE THREAD

**Issue by yunshaochu** [hymbz/ComicReadScript#138]
我是使用kaggle部署，利用ngrok进行内网穿透的。ngrok生成的url可以正常翻译图片，但我把url写到本插件的“自定义url”时，显示"找不到服务器"，这要怎么处理呢？

**Comment by yunshaochu** [comment]
好像是我api设置的问题

**Comment by yunshaochu** [comment]
kaggle上的笔记如下：

```
# Set up the environment.
!git clone https://github.com/zyddnys/manga-image-translator
%cd manga-image-translator/
!python -m pip install -r requirements.txt
!python -m pip install git+https://github.com/kodalli/pydensecrf.git
!pip install -q pyngrok
```

```
# 填写ngrok的token
ngrokToken = ""
if ngrokToken:
  from pyngrok import conf, ngrok
  conf.get_default().auth_token = ngrokToken
  conf.get_default().monitor_thread = False
  ssh_tunnels = ngrok.get_tunnels(conf.get_default())
  if len(ssh_tunnels) == 0:
      ssh_tunnel = ngrok.connect(5003)
      print('address:'+ssh_tunnel.public_url)
  else:
      print('address:'+ssh_tunnels[0].public_url)


!python -m manga_translator --verbose --mode web --use-gpu

```

**Comment by yunshaochu** [comment]
![90%N~22OF0VUPR$OF$BK6@6](https://github.com/hymbz/ComicReadScript/assets/100759920/bf5ca573-1fb5-477e-8591-0ce57418d30c)
![) MSG%X6Y H26Y17G01 LS5](https://github.com/hymbz/ComicReadScript/assets/100759920/a874121c-5fc1-4260-94b3-6b1d6b92fb51)
"翻译服务"为空白，右侧控制台无报错

**Comment by hymbz** [comment]
首先，github 是可以看到编辑历史的，所以赶紧先去重置 token

**Comment by hymbz** [comment]
然后，不管是 kaggle 还是 ngrok 我都完全没用过也没了解过，所以不是很懂。但之前也有人提到过相关的配置，你可以看下这个 [issus](https://github.com/hymbz/ComicReadScript/issues/95#issuecomment-1737698015) 可能会有用？还有 [这个评论](https://sleazyfork.org/zh-CN/scripts/374903-comicread/discussions/207625) 里的人就是用 ngrok 做的内网穿透，你可以去问问他？

**Comment by hymbz** [comment]
不过你控制台没报错有点奇怪，你点开几下`翻译服务`的选择框，看看有没有报错。

**Comment by yunshaochu** [comment]
谢谢提醒，已经重置token了。
我刚刚又重试了好几遍，控制台依旧没有报错，干脆建了一个代理服务器把请求转发到我本地，一步步调试，最后终于发现了原因：必须在ComicReadScript脚本所在的浏览器上，先打开一遍ngrok提供的url，才能正常使用服务器……
也就是这个问题纯粹是我不熟悉ngrok造成的（
谢谢你，已经可以正常使用了
