### ISSUE TITLE
[Bug]: cotrans api resize-crash

### ISSUE THREAD

**Issue by EnergoStalin** [hymbz/ComicReadScript#139]
Related famous site gallery id: 488565

Not sure who to report but judging all other stuff resizes fine lets assume some images need preprocessing before submitting.

Cleared tampermonkey [har](https://github.com/hymbz/ComicReadScript/files/13980415/resize-crash.json) log.

### Notes:
- Copy pasting image to the cotrans frontend works.
- Downloading archive then translating in PWA works.
- Fresh browser profile reproducible.

**Comment by hymbz** [comment]
This should be reported to cotrans, I'm not sure how to handle it either.

As far as I know, currently cotrans only reduces images larger than 4k. [code link](https://github.com/VoileLabs/cotrans/blob/08992fa0d89e40f22477e90a361823942f2f8c86/userscript/src/utils/core.ts#L28)

**Comment by EnergoStalin** [comment]
The image itself smaller than 4k its like 1280x1780. So it's something with it's format i guess but HOW if it's submitted by web standard.

Also i'm a little bit afraid that cortans repo is slightly dead.

**Comment by hymbz** [comment]
Since there has been no follow-up for a long time, I will close this issue. Feel free to reopen it if needed in the future.
