### ISSUE TITLE
从 ehentai 调用nhentai 完全加载后无法进入阅读模式

### ISSUE THREAD

**Issue by fireattack** [hymbz/ComicReadScript#14]
环境：Win10+Chrome 75+Tampermonkey 4.8.41

1. 打开任意ehentai画廊，例如 https://e-hentai.org/g/1271496/19ce3455ed/
2. 找到下方的nhentai编码，点击，然后之后点下面出现的“Load comic”
3. 等待load完成，点read

应该发生：进入阅读模式
实际发生：点击read无反应，控制台无报错。

其他补充：奇怪的是，在仍在加载时反而可以正常进入阅读模式，但是load完了则不行。

**Comment by hymbz** [comment]
已修复。
