### ISSUE TITLE
绅士漫画不能用了

### ISSUE THREAD

**Issue by chobitsbaby** [hymbz/ComicReadScript#141]
绅士漫画不能用了

**Comment by hymbz** [comment]
我首页点开了几本都可以正常运行啊，可能是和其他插件冲突了？

**Comment by hymbz** [comment]
突然想到，是不是网址问题。目前脚本只支持以下网址：

- [www.wn3.lol]()
- [www.wnacg.com]()
- [wnacg.com]()

你用的是其他网址吗？

**Comment by hymbz** [comment]
脚本已更新，把 [绅士漫画发布页](https://wnacg01.org) 里的网址都给补上了。
