### ISSUE TITLE
[bug]卷轴模式下，手滑动后，会自动向下一小截或者向上一截

### ISSUE THREAD

**Issue by tamendeshijie** [hymbz/ComicReadScript#142]
具体来说，就是使用卷轴模式时，翻动漫画后不会停住，会像单页模式下一样，自动调整这一页居中，但是卷轴模式下，并不希望他页面居中，只希望是，翻到哪里停在哪里。

**Comment by tamendeshijie** [comment]
感谢大佬不断地修bug，十分感谢！

**Comment by tamendeshijie** [comment]
是在笔记本的触摸板使用的时候尤其明显，鼠标滑轮使用幅度小的时候会有一点，但大幅度的时候就会停住，之前几个版本使用并没有出现这些问题

**Comment by tamendeshijie** [comment]
刚实验了一下下，从8.5版本开始出现的问题，包括8.4.3以前的版本并没有这个问题。

**Comment by hymbz** [comment]
已更新修复。~~平时都用的台式，所以上次更新完忘记测试触摸板了（~~

**Comment by tamendeshijie** [comment]
大佬大佬，能不能做一个把漫画放大到与屏幕相符合的选项

**Comment by hymbz** [comment]
> 大佬大佬，能不能做一个把漫画放大到与屏幕相符合的选项

诶，默认不就是这样的吗？是不是把`设置-显示-禁止图片自动放大`这一项打开了？

**Comment by tamendeshijie** [comment]
> > 大佬大佬，能不能做一个把漫画放大到与屏幕相符合的选项
> 
> 诶，默认不就是这样的吗？是不是把`设置-显示-禁止图片自动放大`这一项打开了？

大佬大佬，我说的是卷轴模式，他不是成一列了么，然后这时候这个放大能不能让两边贴合屏幕，有时候我手动用触摸板放大的时候，总会有一小节在外面（具体表现是左右划屏幕，可以滑动，有一小节在屏幕外面），有的漫画他是扫描的，似乎轴有点歪，这时候就会有好大一截在外面

**Comment by tamendeshijie** [comment]
> > 大佬大佬，能不能做一个把漫画放大到与屏幕相符合的选项
> 
> 诶，默认不就是这样的吗？是不是把`设置-显示-禁止图片自动放大`这一项打开了？

       就有一小节是在外面的，也检查过了那个自动放大是正常的，单页模式下不会出现卷轴模式下那种过度放大的问题，但是在卷轴模式下，那个自动放大似乎是无效的。
       我先开启自动放大，这时候漫画完美契合屏幕，但此时开启卷轴模式，不知道为啥会莫名其妙再放大一下，这时候有很小部分内容就在屏幕外面了。
       感谢大佬！这真的是一个完美的漫画阅读器！

**Comment by hymbz** [comment]
原来是指的卷轴模式啊，那个设置是只在翻页模式下生效的😂

不过我这边试了几个漫画都没这个问题，你发一个有这种问题的漫画链接给我吧

**Comment by tamendeshijie** [comment]
> 原来是指的卷轴模式啊，那个设置是只在翻页模式下生效的😂
> 
> 不过我这边试了几个漫画都没这个问题，你发一个有这种问题的漫画链接给我吧

https://exhentai.org/g/2817206/aa07aae9a1/
感谢大佬，就是有一点点的边是在屏幕外面，我尝试看看能不能截图发您
![83774339a2beba3b969750cb6339282](https://github.com/hymbz/ComicReadScript/assets/98198879/16b12911-1b7f-4f42-94b5-461ccb3f104d)
![19cb4b24f0f74d0ca6e80d114a93a1d](https://github.com/hymbz/ComicReadScript/assets/98198879/359069fb-3464-4ec4-8ccc-6913f70a6411)
您可以看见右边那个紫色女生的膝盖，第二张图片就多了一点，就是每次卷轴模式放大后都会比单页模式全屏放大一丢丢

**Comment by hymbz** [comment]
把设置里的`卷轴图片缩放`调到 100% 试试？

**Comment by tamendeshijie** [comment]
> 把设置里的`卷轴图片缩放`调到 100% 试试？

100的话两边会空出好大一个空白嘿嘿嘿

**Comment by tamendeshijie** [comment]
> 把设置里的`卷轴图片缩放`调到 100%

> 把设置里的`卷轴图片缩放`调到 100% 试试？

大佬可能是我屏幕的问题吧哈哈哈，太晚啦，实在是麻烦您啦，我刚尝试了下卷轴图片缩放调整为164差不多是契合我的屏幕，会留下一点点白线，但已经足够啦，嘿嘿，麻烦您啦

**Comment by hymbz** [comment]
啊终于懂了，就是`适合宽度`的缩放方式是吧，没问题，下次更新加上。

**Comment by tamendeshijie** [comment]
> 啊终于懂了，就是`适合宽度`的缩放方式是吧，没问题，下次更新加上。

感谢大佬！！麻烦您啦，大佬早点休息！

**Comment by hymbz** [comment]
更新加上了，切换到卷轴模式后就能在 `设置 - 显示` 下看到 `卷轴图片适合宽度` 这一开关了。

**Comment by tamendeshijie** [comment]
> 更新加上了，切换到卷轴模式后就能在 `设置 - 显示` 下看到 `卷轴图片适合宽度` 这一开关了。

感谢大佬！完美使用！
