### ISSUE TITLE
很喜欢PWA，有些小建议可以在这里反馈嘛？

### ISSUE THREAD

**Issue by Xand233** [hymbz/ComicReadScript#144]
### 具体描述

希望大佬能增加排序逻辑更改和翻译结果单独归类功能

**Comment by hymbz** [comment]
能具体说说吗？需要什么样的排序逻辑？翻译结果单独归类是说只显示翻译图？

**Comment by Xand233** [comment]
> 能具体说说吗？需要什么样的排序逻辑？翻译结果单独归类是说只显示翻译图？

感谢大佬回复，目前遇到的问题：
默认排序逻辑似乎和e站上传的默认排序一样是字典排序，希望能增加自然排序功能
翻译希望增加将多张翻译结果图统一导出至文件夹功能

**Comment by hymbz** [comment]
更新上了，如果没有生效的话就 `ctrl+F5` 一下

**Comment by Xand233** [comment]
> 更新上了，如果没有生效的话就 `ctrl+F5` 一下

感谢大佬
