### ISSUE TITLE
老哥，mangabz上使用好像有问题

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [hymbz/ComicReadScript#145]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

篡改猴

### 使用的浏览器是？

狐猴浏览器

### 问题会在哪个网页上出现？

https://www.mangabz.com/m340743/

### 问题是？

没法使用漫画阅读模式，好像一直在加载图片，但是页面上已经全显示了，图片也没这么多😂这个网站我要翻墙才能进去，不过应该跟问题没关系🤔

![Screenshot_20240202-174143](https://github.com/hymbz/ComicReadScript/assets/54784104/3df68f15-b92d-4d91-853b-5aed5a5e6084)
![Screenshot_20240202-174154](https://github.com/hymbz/ComicReadScript/assets/54784104/f05ae5db-b6cb-4d05-9bea-2265c07d8ee7)

**Comment by tamendeshijie** [comment]
没有啊，我正常使用，你的翻墙节点不太稳定吧

**Comment by tamendeshijie** [comment]
你的那个链接我就可以正常加载阅读，顺带感谢分享网站哈哈哈，我还用其他漫画实验了都是正常的

**Comment by hymbz** [comment]
> 没有啊，我正常使用，你的翻墙节点不太稳定吧

是移动端才有的问题。mangabz 为移动设备单独做了一版网页，但因为我之前没用手机上过 mangabz 所以一直不知道，脚本也没做适配这才出了问题😂

**Comment by tamendeshijie** [comment]
> > 没有啊，我正常使用，你的翻墙节点不太稳定吧
> 
> 是移动端才有的问题。mangabz 为移动设备单独做了一版网页，但因为我之前没用手机上过 mangabz 所以一直不知道，脚本也没做适配这才出了问题😂

辛苦大佬，大佬晚安！我熬不住了哈哈哈

**Comment by SaltedFish-Extreme** [comment]
可以，麻烦老哥了😂说起来我昨天看`yymanhua`，狐猴浏览器没问题，但是kiwi浏览器就使用不了插件，就连网页页面都不大一样，后来发现是因为在kiwi浏览器上启用了`桌面版网站`的选项，可能也是给电脑做了一版网页，漫画单页显示的，插件不能用😂

**Comment by SaltedFish-Extreme** [comment]
![Screenshot_20240203-074010](https://github.com/hymbz/ComicReadScript/assets/54784104/6978d875-4d1f-44e0-aae5-e848f91d1d97)
![Screenshot_20240203-074107](https://github.com/hymbz/ComicReadScript/assets/54784104/7c498191-a0e2-458f-bf11-50bdcbdab2ed)
![Screenshot_20240203-074053](https://github.com/hymbz/ComicReadScript/assets/54784104/f3b4db57-d3e4-43b7-834a-b83ed25e47ce)

**Comment by hymbz** [comment]
mangabz 的移动端 bug 已更新修复。

yymanhua 是因为桌面版不会将图片全都显示出来，需要手动翻页的缘故，所以简易模式没法用，这个倒不算 bug。不过反正只要不开 `桌面版网站` 就好了吧。

**Comment by SaltedFish-Extreme** [comment]
嗯，是这样，没事了，麻烦老哥了😂
