### ISSUE TITLE
百合会启用cloudflare后，下载功能失效

### ISSUE THREAD

**Issue by HmnSn** [hymbz/ComicReadScript#146]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

篡改猴

### 使用的浏览器是？

Chrome

### 问题会在哪个网页上出现？

https://bbs.yamibo.com/forum-30-1.html

### 问题是？

只能下载第一页，后面的都无法下载

**Comment by hymbz** [comment]
试了几个都可以正常下载啊，只是速度和以前相比慢了很多。你发几个无法下载的帖子链接给我吧

**Comment by HmnSn** [comment]
> 试了几个都可以正常下载啊，只是速度和以前相比慢了很多。你发几个无法下载的帖子链接给我吧

今天访问300时发现不会像昨天一样每一次都弹“cloudflare 检查站点连接是否安全”的页面了，下载也恢复正常了。应该是调高了触发验证的阈值
