### ISSUE TITLE
老哥，可以适配两个网站的简易阅读模式吗？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [hymbz/ComicReadScript#148]
### 具体描述

[极速漫画](https://m.1kkk.com/manhua432/)
[漫画人](https://www.manhuaren.com/manhua-haizeiwang-onepiece/)
这两个网站用安卓平板浏览漫画都是单页显示的，按钮翻页，还显示不全，需要像卷轴一样下拉看，可以适配下吗😂(需要翻墙看)

启用桌面版网站和不启用的效果一样，横屏竖屏的效果都不大好😭
![Screenshot_20240205-144532](https://github.com/hymbz/ComicReadScript/assets/54784104/9c079db0-b35a-416a-9e15-1e74efc870fe)
![Screenshot_20240205-144803](https://github.com/hymbz/ComicReadScript/assets/54784104/6cfddf4f-1492-4db3-ac52-0421bc30f087)

**Comment by SaltedFish-Extreme** [comment]
哦，还有一个[漫画柜](https://m.manhuagui.com/comic/1128/)😂
![Screenshot_20240205-145734](https://github.com/hymbz/ComicReadScript/assets/54784104/0ae2d6ee-f772-4315-ac57-59adf8aafcd0)

**Comment by SaltedFish-Extreme** [comment]
哦，我刚发现漫画柜启用桌面版网站好像适配了，一开始用的安卓页面😂极速漫画把网址前缀的m去掉，也可以适配😂漫画人就还是那样
![Screenshot_20240205-150354](https://github.com/hymbz/ComicReadScript/assets/54784104/0e928ff6-dbfe-4307-8b41-d2ee68fe96dd)
![Screenshot_20240205-150657](https://github.com/hymbz/ComicReadScript/assets/54784104/b8d5c304-31e8-4ec0-ae59-d812e6be85e2)

**Comment by hymbz** [comment]
极速漫画和漫画人其实和 dm5 算是同一个站点，所以是在脚本支持站点中的，不需要用简易阅读模式。脚本已更新，现在可以正常工作了。
