### ISSUE TITLE
对于copymanga网站的部分漫画无法进入阅读模式

### ISSUE THREAD

**Issue by VanceZhang** [hymbz/ComicReadScript#149]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

Tampermonkey（篡改猴）

### 使用的浏览器是？

Firefox 122.0.1

### 问题会在哪个网页上出现？

https://www.copymanga.tv/comic/jagan/chapter/4ae63246-fc99-11eb-a07f-024352452ce0

### 问题是？

在copymanga中部分漫画的浏览界面无法自动进入阅读模式。
并且右下角悬浮按钮正常显示，点击后会弹出'加载图片中'和‘漫画加载出错’的提示，但依旧无法进入阅读模式。
![{436B4FE0-8EF7-4891-B4E7-F335A1376007}](https://github.com/hymbz/ComicReadScript/assets/22425765/5c8706bc-4c4d-4e2f-94f7-b355188a9135)
![{CB512033-5A93-407f-BA52-751EEF9E0D2F}](https://github.com/hymbz/ComicReadScript/assets/22425765/6a328a4b-536f-4ae2-9b04-a174771f6f60)

**Comment by hymbz** [comment]
已更新修复
