### ISSUE TITLE
kemono调用pwa加载失败

### ISSUE THREAD

**Issue by YURICORN** [hymbz/ComicReadScript#150]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

Tampermonkey

### 使用的浏览器是？

Microsoft Edge 版本 123.0.2420.20 (正式版本) stable应用，beta频道 (64 位)

### 问题会在哪个网页上出现？

https://kemono.su/

### 问题是？

大概下载个百分之十几就会提示加载失败
![image](https://github.com/hymbz/ComicReadScript/assets/43528141/f248b134-86a1-45e2-8fe7-e00581d531f0)

**Comment by hymbz** [comment]
是因为忘了关掉下载的超时限制导致的。。已更新修复。
