### ISSUE TITLE
开源漫画阅读器:Kavita, 能够适配吗?

### ISSUE THREAD

**Issue by zuilintan** [hymbz/ComicReadScript#151]
Github地址: https://github.com/Kareadita/Kavita

当前的简易漫画阅读器无法生效

**Comment by hymbz** [comment]
我用官方的演示站试了下，只要将阅读模式改成卷轴模式，简易模式就能正常加载了。同时还要把滑动手势关掉，不然会误触发。

单独适配挺麻烦的，因为没有一个固定的域名，得用其他方式来判断当前网页是否是 Kavita，所以你先试试简易模式能否满足需求吧。

**Comment by hymbz** [comment]
因为没有回复，所以我就先当简易模式足够满足你的需求，关掉这个 issues 了，有需要可以再重新打开。
