### ISSUE TITLE
[Bug]: kemono.su fails to remember last page mode

### ISSUE THREAD

**Issue by EnergoStalin** [hymbz/ComicReadScript#153]
### 具体描述

Currently 2 page mode is default. I want option to make single page mode default. Never actually use 2 page mode.

**Comment by hymbz** [comment]
The script will remember the reading settings for each website individually. You only need to switch it once on your frequently used websites.

**Comment by EnergoStalin** [comment]
True. Okay then let me make this bug report. On kemono.su it seems to fail remember.

[Open](https://kemono.su/posts/random) -> Go into reading mode -> Change page mode -> Open random post again -> Into reading mode -> Mode not remembered.

Reproducible on fresh browser profile.

**Comment by hymbz** [comment]
Already updated.
