### ISSUE TITLE
  在 manhuagui.com 下載後，zip 內檔案的副檔名後面多出一堆字串

### ISSUE THREAD

**Issue by frank-h** [hymbz/ComicReadScript#155]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

Tampermonkey

### 使用的浏览器是？

Firefox

### 问题会在哪个网页上出现？

https://tw.manhuagui.com/comic/416/3606.html

### 问题是？

跟 #110 類似

zip內的圖檔名：
000.webp?e=1711814400&m=Ckd6Zg1a3UZCoYhcWty9kA

**Comment by hymbz** [comment]
已更新修复
