### ISSUE TITLE
[Feature Request]: Translate current page shortcut

### ISSUE THREAD

**Issue by EnergoStalin** [hymbz/ComicReadScript#156]
### 具体描述

It's nice that you can easily and freely navigate with keyboard which i really like about this script but for translation you forced to use mouse it's inconvenient.

**Comment by hymbz** [comment]
thanks PR, already updated.

**Comment by EnergoStalin** [comment]
Ye thanks you too. You can just leave it closed i intentionally linked issue to pr so it's closed after merge.
