### ISSUE TITLE
对于kemono.su，可否提供一个不加载原图的开关？

### ISSUE THREAD

**Issue by 0093Axis** [hymbz/ComicReadScript#158]
### 具体描述

RT，有些时候打开帖子会有几十张差分图，这时候只是想快速浏览下差分，默认加载的缩略图已经够用了，可否提供一个开关不加载原图？

**Comment by hymbz** [comment]
只是想快速浏览的话，不打开阅读模式直接在原网页上滚动不就行了吗？

**Comment by hymbz** [comment]
久等了，更新加上了，现在可以在网页右下角悬浮按钮的菜单里切换。

**Comment by 0093Axis** [comment]
> 久等了，更新加上了，现在可以在网页右下角悬浮按钮的菜单里切换。

非常感谢！
