### ISSUE TITLE
功能建议: 按原图大小显示，滚动浏览

### ISSUE THREAD

**Issue by SchneeHertz** [hymbz/ComicReadScript#16]
个人比较习惯滚动阅读漫画，像EX自带的Multi-Page的效果，图片按原本大小显示，拼接成一页后用滚动浏览，请问有增加这个功能的计划吗？

**Comment by hymbz** [comment]
没用过 Multi-Page ，是像动漫之家的上下滚动阅读那样吗？实现起来倒是不难，等放暑假有时间写代码后可以加这个功能。

**Comment by SchneeHertz** [comment]
> 没用过 Multi-Page ，是像动漫之家的上下滚动阅读那样吗？实现起来倒是不难，等放暑假有时间写代码后可以加这个功能。

是的，和动漫之家的阅读模式类似

**Comment by hymbz** [comment]
已更新

**Comment by SchneeHertz** [comment]
感谢
