### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by wechatplan** [hymbz/ComicReadScript#164]
### 在提交 issue 之前，请先确认

- [x] 脚本已更新至最新版本

### 使用的油猴扩展是？

Tampermonkey

### 使用的浏览器是？

EDGE

### 问题会在哪个网页上出现？

https://e-hentai.org/

### 问题是？

GPT3.5翻译后结果显示空白，选择其他翻译后一直卡在翻译文本或整合文本；取消后再次翻译显示等待翻译而导致翻译被卡住

**Comment by hymbz** [comment]
是用的 Cotrans 还是自己部署的 manga-image-translator？

**Comment by wechatplan** [comment]
用的 Cotrans

**Comment by hymbz** [comment]
> GPT3.5翻译后结果显示空白，选择其他翻译后一直卡在翻译文本或整合文本

这个我也遇到过，是 Cotrans 的问题，得去那边提 issues。

> 取消后再次翻译显示等待翻译而导致翻译被卡住

翻译是没法取消的，只是发了个新请求过去，还是得等之前发过去的翻译完才能继续。另外毕竟是公共的服务，也有可能就是单纯的有其他人也在用，所以在排队吧。
