### ISSUE TITLE
大佬，翻译可以增加gpt4的选项吗

### ISSUE THREAD

**Issue by Xand233** [hymbz/ComicReadScript#166]
### 具体描述

貌似只有gpt3.5模型，官方文档似乎支持gpt4模型

**Comment by hymbz** [comment]
是说 Cotrans 还是本地部署？不过不管哪个都不是脚本能控制的就是了（

Cotrans 需要服务器支持才行，可以去 issues 提建议。本地部署的话目前好像只能自己去改文件， 详见 zyddnys/manga-image-translator#552
