### ISSUE TITLE
希望支持http://www.92mh.com/

### ISSUE THREAD

**Issue by dunkeng** [hymbz/ComicReadScript#167]
### 具体描述

http://www.92mh.com/
脚本不支持这个网站的漫画，希望支持

**Comment by hymbz** [comment]
在页面右边把翻页模式改成上下滚动阅读就能用简易阅读模式支持了。

如果嫌图片加载太慢的话可以搭配使用「[圖片全載](https://sleazyfork.org/zh-CN/scripts/463305)」，不过这个网站默认没有启用，要在代码里搜索 `www.92mh.com`，把下一行的 `enable: 0,` 改成 `enable: 1,`。
