### ISSUE TITLE
cent載入後看不到頁碼

### ISSUE THREAD

**Issue by leadra** [hymbz/ComicReadScript#168]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

Violentmonkey

### 使用的浏览器是？

Cent Browser 版本 5.1.1130.82 (正式版本) (64 位元) (Chromium 118.0.5993.159)

### 问题会在哪个网页上出现？

https://www.dm5.com/m1499647/

### 问题是？

載入完成後，看不到頁碼
還在載入時還可以看到

原本以為是瀏覽器字體，後來改微軟正黑體也一樣
不過chrome正常，可能是我瀏覽器問題
![image](https://github.com/hymbz/ComicReadScript/assets/67009996/fa3ee56a-5b90-4142-9495-155055a3703a)
![image](https://github.com/hymbz/ComicReadScript/assets/67009996/3cdefb6f-8954-4577-b92a-b6959456bfb4)
![image](https://github.com/hymbz/ComicReadScript/assets/67009996/912c60af-a4c3-46cb-a652-974de7bb3c1e)

chrome正常，chrome的選項不知為何好小
![image](https://github.com/hymbz/ComicReadScript/assets/67009996/994ccd5b-fdfa-467b-b445-db4e5bd7d305)

**Comment by hymbz** [comment]
> 載入完成後，看不到頁碼

我这边用同样的环境无法复现。你那边能够稳定复现吗？是所有漫画都会有这问题吗？

感觉可能是和其他图片相关的脚本或插件有冲突。

> chrome的選項不知為何好小

是说和 Cent Browser 相比更小？是因为页面缩放不一样导致的吧。

**Comment by leadra** [comment]
是啊 ，測試了好幾個，copy的也是
插件全關，保留Violentmonkey
我的cent是最近覆蓋新版本上去的，也許跟這個有關吧
大小的話，以為是瀏覽器的最小字型，chrome有設定加大，但一樣小

那就不用管它了，大概是我以前弄過啥設定，這幾天正好要重灌，到時候觀察看看
感謝作者特地用同樣環境測試，勞煩你了
非常感謝!
![image](https://github.com/hymbz/ComicReadScript/assets/67009996/bfdb7f5c-0e1b-4095-91ec-b570947373b7)
