### ISSUE TITLE
使用dm5，翻頁後左邊會暫留上頁內容

### ISSUE THREAD

**Issue by hooowbanban** [hymbz/ComicReadScript#169]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

Tampermonkey（篡改猴）

### 使用的浏览器是？

google chrome

### 问题会在哪个网页上出现？

https://www.dm5.com/

### 问题是？

![0605](https://github.com/hymbz/ComicReadScript/assets/168960785/25a2011e-ffb2-4286-9e70-5aeea94f86a8)
作者您好~
如圖片所示
使用dm5瀏覽時
翻頁後左側會暫留上一頁的內容(不管是往上或往下翻頁)
想請問此狀況有解嗎

**Comment by hymbz** [comment]
我这边测试的情况有点不一样，是在翻页后图片没有居中而是靠左显示，然后在移动图片时才会出现图片暂留，对此已经更新修复了。你更新试下有没有成功解决。

**Comment by hooowbanban** [comment]
2024/06/10 更新測試目前已無問題，感謝
