### ISSUE TITLE
希望增加对telegra.ph的支持

### ISSUE THREAD

**Issue by ASIjacket** [hymbz/ComicReadScript#17]
telegra.ph有很多纯图片的漫画搬运 希望可以增加支持

**Comment by ASIjacket** [comment]
网页结构就是在 <article>标签里一堆<img>
尝试改了一一下 因为水

> telegra.ph有很多纯图片的漫画搬运 希望可以增加支持

**Comment by hymbz** [comment]
telegra.ph 的可以直接用简易漫画阅读模式来看，之前因为 bug 导致不能正确判断使用哪些图片，这次更新后可以了。

**Comment by ASIjacket** [comment]
感谢支持
