### ISSUE TITLE
Not work on adguard android

### ISSUE THREAD

**Issue by bropines** [hymbz/ComicReadScript#170]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

Adguard for android

### 使用的浏览器是？

Chrome

### 问题会在哪个网页上出现？

All

### 问题是？

The problem arises simply when importing the script. The adgruppd refuses to import it, despite the fact that it imports any others. 

![Screenshot_2024-06-15-13-33-35-941_com adguard android](https://github.com/hymbz/ComicReadScript/assets/57861007/abb6fa7b-4073-4f8a-97cb-41070a5221cd)

here is the documentation of the adguard:
https://adguard.com/kb/general/userscripts/

before some kind of adguard update, everything worked, then the button stupidly stopped appearing, and the script could not update. Installing older versions of the extension did not help.

**Comment by hymbz** [comment]
I didn't encounter this issue here. The script was successfully imported, and the URL used is: `https://update.sleazyfork.org/scripts/374903/ComicRead.user.js`.

![photo_2024-06-15_21-35-13](https://github.com/hymbz/ComicReadScript/assets/17750128/9463b625-26b7-4c00-b079-370ce2e020f7)

From the error message, it seems that there might be an issue with the URL you entered or a network problem.

**Comment by bropines** [comment]
> I didn't encounter this issue here. The script was successfully imported, and the URL used is: `https://update.sleazyfork.org/scripts/374903/ComicRead.user.js`.
> 
> ![photo_2024-06-15_21-35-13](https://private-user-images.githubusercontent.com/17750128/339989886-9463b625-26b7-4c00-b079-370ce2e020f7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NjI4MzksIm5iZiI6MTcxODQ2MjUzOSwicGF0aCI6Ii8xNzc1MDEyOC8zMzk5ODk4ODYtOTQ2M2I2MjUtMjZiNy00YzAwLWIwNzktMzcwY2UyZTAyMGY3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDE0NDIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4YzkzMWFhZmFhNGM0Zjk4MmM4OTQzNGRhNWFmZGVmNDVmNTE5ZmQzOWM2ODhjZjkxNzc5NWRlODY0NGY4ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yV1oi7pfhS8DJqoF9vwcIm3UOKEgJi2r6OIll9BRUk0)
> 
> From the error message, it seems that there might be an issue with the URL you entered or a network problem.

I thought so too, but I deliberately took it and tried to upload the file. I assume you don't have the nigthly version?
(maybe speak russian?)

**Comment by hymbz** [comment]
Do you mean the nightly version installed through this link: <https://agrd.io/android_nightly>? I tried it, and it can also import scripts normally.

Try using the GitHub link: `https://raw.githubusercontent.com/hymbz/ComicReadScript/master/ComicRead.user.js`.

Additionally, I do not speak Russian. I'm using adguard for Android for the first time, switching to Russian to make sure I'm on the right page.

**Comment by bropines** [comment]
https://github.com/hymbz/ComicReadScript/assets/57861007/f26eaeff-b994-4321-8d21-2cd1b79e4a85

Is this some kind of joke? I installed version (on the emulator, it has the Internet, checked it on TikTok) 4.4.1 and I once installed the script on it. But now it doesn't work. What version do you have?

**Comment by bropines** [comment]
If I wrote anything to Adgard, where I was sent far and long
https://github.com/AdguardTeam/AdguardForAndroid/issues/5354#issuecomment-2168430934

**Comment by hymbz** [comment]
In my test, this error message appears due to network issues.

Because of the network situation in China, I need to enable Clash for Android to access the script's URL. In the video, I first turned off Clash, and then this error message appeared when importing the script. After turning on Clash, the problem was resolved.

https://github.com/hymbz/ComicReadScript/assets/17750128/2ded12d1-f5be-499a-a032-7924d95112e3

**Comment by hymbz** [comment]
Try replacing the `@resource` section of the code with the following, then save it as a file and try importing it to see if it works?


```js
// @resource        solid-js https://cdn.jsdelivr.net/npm/solid-js@1.8.12/dist/dev.cjs
// @resource        fflate https://cdn.jsdelivr.net/npm/fflate@0.8.1/umd/index.js
// @resource        qr-scanner https://cdn.jsdelivr.net/npm/qr-scanner@1.4.2/qr-scanner.legacy.min.js
// @resource        dmzjDecrypt https://greasyfork.org/scripts/467177/code/dmzjDecrypt.js?version=1207199
// @resource        solid-js|store https://cdn.jsdelivr.net/npm/solid-js@1.8.12/store/dist/dev.cjs
// @resource        solid-js|web https://cdn.jsdelivr.net/npm/solid-js@1.8.12/web/dist/dev.cjs
```

**Comment by bropines** [comment]
works. however, I had to turn off the filtering and turn on the German VPN. it remains to understand what is being blocked here or who is blocking users from Russia

**Comment by hymbz** [comment]
Can the Russian network access <https://registry.npmmirror.com/fflate/0.8.1/files/umd/index.js>?

**Comment by bropines** [comment]
> Can the Russian network access [registry.npmmirror.com/fflate/0.8.1/files/umd/index.js](https://registry.npmmirror.com/fflate/0.8.1/files/umd/index. js)?

Well, on the phone and PC he opens it. I tried running curl in termux without a VPN, it pings all links. But when I also import the file, it does not import, saying that the link is incorrect.

I also can't see the UI in Chrome.

**Comment by bropines** [comment]
I tried to upload it separately in extensions in the Yandex browser, it works, but through adg it doesn’t. At the same time, the [Yandex video translator](https://github.com/ilyhalight/voice-over-translation) works quietly. 

https://github.com/hymbz/ComicReadScript/assets/57861007/b89f59a9-7e39-45b2-a39d-af9606839aad

**Comment by hymbz** [comment]
Because I need to use a VPN to access many websites, I can't test too many of them.

Some websites malfunction because AdGuard lacks support for `GM.addStyle`. I have already released an updated version to address this issue. However, there are still some websites that don't work properly, and I can't pinpoint the exact reason.

**Comment by bropines** [comment]
> Because I need to use a VPN to access many websites, I can't test too many of them.
> 
> Some websites malfunction because AdGuard lacks support for `GM.addStyle`. I have already released an updated version to address this issue. However, there are still some websites that don't work properly, and I can't pinpoint the exact reason.

I test. I’ll write what it is and how it works.

**Comment by hymbz** [comment]
Try importing the script through the URL again, it might work now.

**Comment by bropines** [comment]
> Try importing the script through the URL again, it might work now.

The import works if I add the lines you wrote above to the file, but the link does not work.  It also does not work on hitomi and exhentai. How stupid is it to stupidly display the button, and not through gm.style? Or then do we need to rework the entire code?

**Comment by hymbz** [comment]
Try this link: <https://github.com/hymbz/ComicReadScript/raw/master/ComicRead-AdGuard.user.js>

**Comment by bropines** [comment]
> Try this link: [`master`/ComicRead-AdGuard.user.js (raw)](https://github.com/hymbz/ComicReadScript/raw/master/ComicRead-AdGuard.user.js)

Not on the first try (it looks like there are already bugs on the adguard side), but it was imported, and even unlike a regular script, it displayed a list of sites that are supported. Import works, but Yuai does not appear yet...

**Comment by hymbz** [comment]
Because Adguard does not support `GM_registerMenuCommand`, it is not possible to use the "Simple Reading Mode". Therefore, I created another version of the script, removing the related functionality and making the script run only on specified websites.

The reason why it can't run on hitomi is probably because the ad filtering rules you are using contain `hitomi.la##+js(noeval)`, which prevents the script from running properly. You need to add a filtering rule `@@||hitomi.la^$jsinject`.

uBlock Origin extension also needs to add a rule.

```
@@injections.adguard.org
hitomi.la#@#+js(noeval)
hitomi.la#@#+js(abort-on-property-read, open)
```

**Comment by hymbz** [comment]
Running the script through Adguard will cause the script to be blocked by the ad-blocking software. It is necessary to troubleshoot and modify the relevant blocking rules. Therefore, it is more recommended to use the Tampermonkey extension to run it.

**Comment by bropines** [comment]
If you add a rule to adguard, then everything works, and even the button display.
`@@||hitomi.la^$jsinject`

![IMG_20240701_144309](https://github.com/hymbz/ComicReadScript/assets/57861007/43830877-601a-4b18-9eed-1a0a9a47ae92)

**Comment by bropines** [comment]
I can try the rules for other sites and write where it works and where it doesn't.

**Comment by hymbz** [comment]
Since the script can now be imported and run normally, is this issue considered resolved?

**Comment by bropines** [comment]
I made such filters. Stupidly took them from the code and from the readme

```adblock
@@||bbs.yamibo.com^$jsinject
@@||www.yamibo.com^$jsinject
@@||manhua.idmzj.com^$jsinject
@@||e-hentai.org^$jsinject
@@||nhentai.net^$jsinject
@@||www.yurifans.com^$jsinject
@@||www.copymanga.com^$jsinject
@@||www.ponpomu.com^$jsinject
@@||terra-historicus.hypergryph.com^$jsinject
@@||18comic.vip^$jsinject
@@||www.manhuagui.com^$jsinject
@@||www.manhuadb.com^$jsinject
@@||www.dm5.com^$jsinject
@@||www.wnacg.com^$jsinject
@@||mangabz.com^$jsinject
@@||komiic.com^$jsinject
@@||www.comicabc.com^$jsinject
@@||www.77mh.nl^$jsinject
@@||anchira.to^$jsinject
@@||kemono.su^$jsinject
@@||nekohouse.su^$jsinject
@@||welovemanga.one^$jsinject
@@||cdn.jsdelivr.net^$jsinject
@@||yamibo.com^$jsinject
@@||dmzj.com^$jsinject
@@||idmzj.com^$jsinject
@@||exhentai.org^$jsinject
@@||hath.network^$jsinject
@@||hypergryph.com^$jsinject
@@||copymanga.\w{2,6}^$jsinject
@@||mangacopy.com^$jsinject
@@||xsskc.com^$jsinject
```

**Comment by hymbz** [comment]
Thank you very much 🙏. I have added relevant notes and referenced this issue in the README.
