### ISSUE TITLE
Firefox 上百合会出现多余的功能按钮并显示乱码

### ISSUE THREAD

**Issue by omvjro** [hymbz/ComicReadScript#172]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

Tampermonkey（篡改猴）

### 使用的浏览器是？

Firefox

### 问题会在哪个网页上出现？

https://bbs.yamibo.com/forum.php?mod=viewthread&tid=545513

### 问题是？

首先感谢开发者，用了很久了，越来越好用！下面是遇到问题的截图：
![截图](https://github.com/hymbz/ComicReadScript/assets/144692181/5026c95d-4a35-4318-a7a0-d7b55f7950fd)

**Comment by hymbz** [comment]
从乱码的字数长度和排序来看，感觉应该是原本存储的配置乱码了导致的。总之先针对这个原因更新了脚本，你试试解决了没。

**Comment by omvjro** [comment]
好了，感谢！
