### ISSUE TITLE
漫画放大功能异常

### ISSUE THREAD

**Issue by ChibaCityBamboo** [hymbz/ComicReadScript#173]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

Tampermonkey

### 使用的浏览器是？

Chrome

### 问题会在哪个网页上出现？

https://www.manhuagui.com/?desktop

### 问题是？

进入漫画阅读界面后漫画放大出现问题，用触控板只能放大部分固定画面，无法自由移动漫画分页。鼠标滚轮也只能翻页而不能在已放大的状态下控制缩放，上一个版本完全没有这种问题。

**Comment by hymbz** [comment]
只能放大部分固定画面无法自由移动是什么意思？放大后没办法拖动？

滚轮无法翻页这是刚更新改的，是为了能在保持缩放的状态下用滚轮翻页，用 `Alt + 滚轮` 就可以了。

**Comment by ChibaCityBamboo** [comment]
> 只能放大部分固定画面无法自由移动是什么意思？放大后没办法拖动？
> 
> 滚轮无法翻页这是刚更新改的，是为了能在保持缩放的状态下用滚轮翻页，用 `Alt + 滚轮` 就可以了。

是的，放大图片以后就给固定死了，比如我放大右边的页面就无法拖动看到左边的页面。如果不放大直接看的话我的电脑屏幕就相当于一个32开单行本的大小，有些电子版比较模糊细节看不清

**Comment by hymbz** [comment]
已更新修复

**Comment by hymbz** [comment]
我又试了下确实好了啊，你脚本真的有更新成功吗？

**Comment by ChibaCityBamboo** [comment]
> 我又试了下确实好了啊，你脚本真的有更新成功吗？

ok了，多谢兄弟😂
