### ISSUE TITLE
android 折叠屏双页模式没法识别

### ISSUE THREAD

**Issue by winoros** [hymbz/ComicReadScript#174]
### 具体描述

不知道是不是因为比例太方了。。像小米的内屏是 2488x2224，vivo 的内屏是半径八两的 2480×2200，华为是 2496 × 2224。。所以自动识别都放的是单页。。

不知道处理这种接近 1:1 的屏幕的双页模式改动大不大

**Comment by winoros** [comment]
```
export const isOnePageMode = createRootMemo(
  () =>
    store.option.onePageMode ||
    store.option.scrollMode.enabled ||
    store.isMobile ||
    store.imgList.length <= 1,
);
```

咦 这里看起来好像是直接判断的，不过 Firefox 的 agent 已经被直接改成 `Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0` 了

然后我看了下
```
/** 滚动条位置 */
export const scrollPosition = createRootMemo(
  (): State['option']['scrollbar']['position'] => {
    if (store.option.scrollbar.position === 'auto') {
      if (store.isMobile) return 'top';
      if (isAbreastMode()) return 'bottom';
      // 大部分图片都是宽图时，将滚动条移至底部
      return store.defaultImgType === 'long' ? 'bottom' : 'right';
    }

    return store.option.scrollbar.position;
  },
);
```

滚动条是放在右边的，看起来 isMobile 也没被设成 true。。 感觉不太能对得上为啥双页模式失败了。。

![image](https://github.com/user-attachments/assets/7d38d60d-ee2c-4657-a48c-93f98f944953)

**Comment by winoros** [comment]
o `state.proportion.单页比例 = Math.min(width / 2 / height, 1);` 看起来是这里？

**Comment by hymbz** [comment]
脚本会根据显示窗口的比例来判断图片类型，所以只有在宽屏上才能显示双页。[参考图](https://www.figma.com/design/h0x2ZHVh3P3bCbnszonRqk/%E6%BC%AB%E7%94%BB%E5%8F%8C%E9%A1%B5%E9%98%85%E8%AF%BB%E6%AF%94%E4%BE%8B%E5%9B%BE?node-id=0-1)

作为从脚本初版沿用至今没有改过的设定，我也有点记不清当初为啥要这样搞不用固定比例（）。不过虽然依稀回忆起了一些原因，但最主要的原因应该还是因为我莫名的对 `图片显示高度=显示窗口高度` 有执念吧😂。也因此我在刚看到你这问题时是非常疑惑的，因为我完全想象不出在 1:1 的屏幕上要怎么显示双页模式，想了半天才发现只要不让图片顶天立地就好了，然后才发现我有这么个奇怪的执念。

抛开莫名奇妙的执念，这个设定也是以前想用于适配手机平板的方式，毕竟在显示窗口不够宽的时候还显示为双页就会导致图片缩放得太小看不清字，也会导致上下出现大片空白。因为我还没摸过折叠屏所以问一下，在折叠屏上双页显示图片还看得请字吗？真的有必要在非宽屏上使用双页模式吗？

只不过无论如何，现在想想感觉判断图片类型确实还是用固定比例来判断比较合适，显示窗口宽度不够自动变单页模式应该作为一个默认开启的设置项让人可以关掉才对。所以即使你对上面问题回答了否，我之后也早晚是要改的，只是时间早晚问题。

**Comment by winoros** [comment]
![Screenshot_2024-07-26-18-15-11-518_org mozilla firefox_beta](https://github.com/user-attachments/assets/34295a36-01fb-42c4-b9fd-ab1d0809ecfb)

横过来黑边其实还好，对于日漫来说单页的大小其实还是略大于直板机单页模式的单页大小的。

**Comment by winoros** [comment]
>图片显示高度=显示窗口高度

太方了就是没法这样搞:joy: 我提issue之前也试过横向卷轴，因为放不下两页所以遇到跨页还是不方便。（eh上的r18这种很少有单页）的我就直接横向卷轴了（

**Comment by hymbz** [comment]
脚本已更新

**Comment by winoros** [comment]
好耶！

**Comment by hymbz** [comment]
上次更新因为想说除了我应该没人有这种奇怪的执念，所以就偷懒没搞自动切换单双页的功能，没想到还是有人需要这个功能的😂（[greasyfork](https://sleazyfork.org/zh-CN/scripts/374903/discussions/253166)），所以又更新加上了。

为了尽量只在平板手机的横竖屏转换时自动切单双页，现在用于判断的屏幕宽高比是1:1，宽度大于高度时双页否则单页。如果脚本更新后你的折叠屏会受到影响，把 `设置-显示-自动切换单双页模式` 关掉再手动切换到双页模式就好。

**Comment by winoros** [comment]
更新试了下还不影响，还好
