### ISSUE TITLE
[BUG] 未适配e-/exhentai的多标签集上色

### ISSUE THREAD

**Issue by Hayakee** [hymbz/ComicReadScript#175]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

Tampermonkey（篡改猴）

### 使用的浏览器是？

Google Chrome 版本 127.0.6533.73（正式版本）（64 位）

### 问题会在哪个网页上出现？

e-/ex所有画廊详情页

### 问题是？

我是e站的捐赠用户，可以使用多标签集，点击My Tags进入默认显示Female标签集，画廊上只会对Female标签集中的tag上色，而其他标签集没有。
![image](https://github.com/user-attachments/assets/6b17d3c0-6e7a-465a-8a5b-a7a1ff699f8c)
![image](https://github.com/user-attachments/assets/e6b78695-53cb-499c-91c5-8565fb977f31)
![image](https://github.com/user-attachments/assets/522dfa3b-2c4c-44a5-8413-6986dc08fc7b)
这是具体的画廊详情页：
![image](https://github.com/user-attachments/assets/b2e7ff19-4125-47a8-8141-b3df0938888b)
![image](https://github.com/user-attachments/assets/4c7b82ca-35db-4e96-a060-77c072b7fd5d)
可以看到汉语和翻译没有上色，正太也没有上色。
猜测是脚本只读取了默认标签集而没有遍历所有标签集导致的。

**Comment by hymbz** [comment]
是因为我没捐赠也找不到人可以测试所以就偷懒没搞（

总之先写了一版出来 <https://gist.github.com/hymbz/de7c0ab2fee305ddfec0f1b3e8b6898c>，你试试可以正常运行吗

顺便请你帮忙看下运行速度怎么样，这个测试版会在右下角弹窗显示进度，我这边只有默认标签集的情况下耗时是四百毫秒左右，不知道标签集数量变多后会慢多少。还有跳过禁用标签集的测试也拜托了🙏

运行日志会打印在 F12 控制台里，如果有问题的话得麻烦你截下控制台的图

**Comment by Hayakee** [comment]
非常感谢开发者，处理速度好快。

> 你试试可以正常运行吗

正常运行。

> 运行速度怎么样

目前测试来看最慢是1000ms左右。

> 跳过禁用标签集的测试

没有问题，正常跳过。
![image](https://github.com/user-attachments/assets/e398076d-35e6-4eff-a34a-201c19018fe4)

Ps：我配合EhSyringe一起使用，画廊详情页面的“load comic”和汉化文本不太搭配，所以我改成“加载漫画”了。
![image](https://github.com/user-attachments/assets/e41a88e6-5b1a-46db-8285-d11e60a5e39a)
