### ISSUE TITLE
请问能否将鼠标滚轮改回缩放功能？

### ISSUE THREAD

**Issue by ChibaCityBamboo** [hymbz/ComicReadScript#177]
### 具体描述

以前我都是触控板放大漫画以后用鼠标滚轮控制页面大小，A/D键翻页。一话一话看的话每一次都要重新放大（这里要是加个记忆上次缩放大小或者自动缩放成25K/16K的按键也行），不过一卷一卷看的话就没啥问题了。更新以后鼠标滚轮成了翻页，跟A/D键的功能有点重合了，不知道能不能改回去，多谢大佬

**Comment by hymbz** [comment]
这个改动主要是为了能在缩放状态下用滚轮翻页才改的，详见 [论坛讨论贴](https://bbs.saraba1st.com/2b/forum.php?mod=redirect&goto=findpost&ptid=1795100&pid=65590190)。感觉你的需求和他一样？

以前是类似图片查看器的逻辑，在缩放后进入缩放模式，所以可以直接用滚轮调整。只不过在我看来滚轮滚动也是属于翻页的快捷键之一，应该和键盘按键效果一致。所以现在就改成类似浏览器的逻辑了，只有在按下对应修饰键的情况下才能使用滚轮调整缩放。

你是不是不知道现在要按修饰键来缩小？因为我感觉这个改动影响应该不大所以我就没写进更新公告里，现在想想对于之前用过缩放功能的老用户来说没有公告确实很容易造成迷惑（

我看原帖里他好像也并不在意缩放后用滚轮翻页，我自己更是基本不用缩放功能完全无所谓，所以就把选择权交给你吧，看完我上面的解释后，你觉得哪种更好更自然？如果是现在这种我就在之后的更新公告里补上说明，不然的话我就改回去了。

**Comment by ChibaCityBamboo** [comment]
> 这个改动主要是为了能在缩放状态下用滚轮翻页才改的，详见 [论坛讨论贴](https://bbs.saraba1st.com/2b/forum.php?mod=redirect&goto=findpost&ptid=1795100&pid=65590190)。感觉你的需求和他一样？
> 
> 以前是类似图片查看器的逻辑，在缩放后进入缩放模式，所以可以直接用滚轮调整。只不过在我看来滚轮滚动也是属于翻页的快捷键之一，应该和键盘按键效果一致。所以现在就改成类似浏览器的逻辑了，只有在按下对应修饰键的情况下才能使用滚轮调整缩放。
> 
> 你是不是不知道现在要按修饰键来缩小？因为我感觉这个改动影响应该不大所以我就没写进更新公告里，现在想想对于之前用过缩放功能的老用户来说没有公告确实很容易造成迷惑（
> 
> 我看原帖里他好像也并不在意缩放后用滚轮翻页，我自己更是基本不用缩放功能完全无所谓，所以就把选择权交给你吧，看完我上面的解释后，你觉得哪种更好更自然？如果是现在这种我就在之后的更新公告里补上说明，不然的话我就改回去了。

我没NGA账号看不了帖子😂不过我大概明白你的意思。修饰键那个放的实在是太太太太大了，拖起来也不方便，我都是用触控板手动缩放的。用其他漫画平台举例的话，哔哩哔哩漫画的翻页也是滚轮，但是他缩放最大限制在大概16开（杂志大小）左右？所以缩放一次就能达到比较理想的标准。这个不知道需不需要投个票征集一下其他用户的意见什么的，如果滚轮不改的话你把缩放大小限制到16K也行。

https://github.com/user-attachments/assets/48d7e59c-148f-4e35-8857-8d98b9f7fecc

**Comment by hymbz** [comment]
啊不是，我是说用 `alt/ctrl + 滚轮` 来缩小😂

**Comment by hymbz** [comment]
因为 greasyfork（[链接](https://sleazyfork.org/zh-CN/scripts/374903-comicread/discussions/253975)）那有人先回复选了保持现状，所以这次更新就先不改回去了，只在更新公告里补上改动的说明。

另外因为我预想中的缩放是用来看漫画上那些对话框外的小字，所以侧边栏放大按钮的缩放倍数才会那么高。这次更新后缩放比例将作为设置项保存，也可以在设置里进行修改了（可以直接用上下方向键增减数值）。

**Comment by ChibaCityBamboo** [comment]
好的，那应该没事了。还有个问题就是我设置放大大小以后又出现了无法用鼠标移动的异常（可以翻页但是鼠标拖动不了画面）

https://github.com/user-attachments/assets/ec046222-457d-4c53-9b68-f8b3849f4c6e

**Comment by ChibaCityBamboo** [comment]
> 已更新修复
