### ISSUE TITLE
漫画每次翻页都会加载

### ISSUE THREAD

**Issue by ChibaCityBamboo** [hymbz/ComicReadScript#178]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

Tampermonkey

### 使用的浏览器是？

chrome

### 问题会在哪个网页上出现？

https://www.manhuagui.com/?desktop

### 问题是？

进入漫画界面后完全不自动加载页数，每次翻页时才会加载，甚至往回翻页都会加载

**Comment by ChibaCityBamboo** [comment]
经过测试以后发现此问题会不时发生。有些卷数的加载没有问题，但有些卷数则完全不加载。

https://github.com/user-attachments/assets/2603f527-d7d4-4c84-89ec-c2931942a01d

**Comment by hymbz** [comment]
是固定那个卷数不加载，还是随机的概率出现？

**Comment by hymbz** [comment]
能再发几个例子的链接吗，视频里这个我这边测试无法复现

**Comment by ChibaCityBamboo** [comment]
OK了，多谢大佬
