### ISSUE TITLE
快捷评分 怎么不好使呀

### ISSUE THREAD

**Issue by lhj5426** [hymbz/ComicReadScript#179]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

Tampermonkey

### 使用的浏览器是？

EDGE

### 问题会在哪个网页上出现？

https://exhentai.org/?f_search=chinese+%22-%E8%8E%89%E8%B5%9B%E7%89%B9%E6%B1%89%E5%8C%96%22+%22-%E9%9C%A7%E5%90%B9%E5%BC%A5%E7%94%9F%22+%22-%E6%A9%84%E6%A6%84%E6%B1%89%E5%8C%96%22+%22-%E9%80%8F%E6%98%8E%E5%A3%B0%E5%BD%A9%22+-other:webtoon%24+-uploader:quanbuzhineng+-uploader:TMDlixin250+-uploader:archen+-uploader:%E6%AB%BB%E4%BA%95%E6%99%AF%E5%92%8C+-uploader:%E6%AE%8B%E6%9C%88%E4%B8%B6&f_cats=1017

### 问题是？

大佬  这个 快捷评分 
让列表页显示的评分不再只是摆设，而是和详情页一样可以直接点击修改。

是怎么用的 是在缩略图模式下的 
![image](https://github.com/user-attachments/assets/186349d1-cf15-4c89-ae54-9bd22a1f4fef)
这里使用吗  但是 点 了没反应呀 ？ 可以说一下正确的使用姿势吗

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/8dc7d72e-8cdf-49a9-abae-25ac4eef5eca)
 这里应该是 启动了吧 ？

**Comment by hymbz** [comment]
是这里没错，也的确启动了。正常就是跟详情页一样，鼠标在上面移动的时候也能看到五星跟着动，点击下去就评分了。

看截图可能是和其他脚本冲突了？关掉其他修改界面的脚本再试试

**Comment by lhj5426** [comment]
嗯 确实是有冲突 
不过 。。。 我关闭之后又挨个打开试想找到 冲突的脚本
结果 每打开一个刷新一下页面 一个一个累加 又累加到如 帖子图里的全部 脚本 结果
现在 还好使  很其他 总之打扰了 哈哈 谢谢
