### ISSUE TITLE
漫画柜失效

### ISSUE THREAD

**Issue by hojosanae** [hymbz/ComicReadScript#18]
漫画柜界面失效

**Comment by hymbz** [comment]
具体是什么问题？我这里用五等分测试还能正常阅读

**Comment by hojosanae** [comment]
不能跳转，试了下五等分：https://www.manhuagui.com/comic/22843/450839.html，也没有跳转
https://i.loli.net/2019/09/01/VlzOPFv7JfTxUdg.png

**Comment by hymbz** [comment]
抱歉这几天有事回复晚了。
我这边试是没问题的，你用的是什么浏览器？脚本是最新的吗？
也有可能是和其他脚本或浏览器扩展发生了冲突，禁用掉其他脚本和扩展后还这样吗？

**Comment by kyonkoism** [comment]
我也没法正常观看被看被封的漫画
http://manhua.dmzj.com/guainvqgdngzsglqz
比如怪女，看的掉标题界面，点进去后就失效弹出了，我是chrome浏览器，油猴只装了这个插件

**Comment by hymbz** [comment]
那我也想不到原因了。。。。

**Comment by kyonkoism** [comment]
> 那我也想不到原因了....

问了下官博，说是版本大更新了，估计是和这个有关吧

**Comment by kyonkoism** [comment]
今天能用了，大佬牛逼

**Comment by TataraMo** [comment]
我這裡也是，沒辦法雙頁觀看了

**Comment by TataraMo** [comment]
https://sm.ms/image/F8PDAK94oGOawl5
https://sm.ms/image/JOAulIXcEg4ydMf

**Comment by hymbz** [comment]
已修复。

是因为漫画柜前端更新导致的，之前获取图片地址的方法失效了。之前漫画柜大概是在AB测试吧，所以那时 @kyonkoism 使用脚本会失效而我这里没事。
