### ISSUE TITLE
画廊外评分和这个脚本冲突

### ISSUE THREAD

**Issue by lhj5426** [hymbz/ComicReadScript#180]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

Tampermonkey

### 使用的浏览器是？

EDGE

### 问题会在哪个网页上出现？

https://exhentai.org/?f_cats=1017&f_search=%22-%E8%8E%89%E8%B5%9B%E7%89%B9%E6%B1%89%E5%8C%96%22+%22-%E9%9C%A7%E5%90%B9%E5%BC%A5%E7%94%9F%22+%22-%E6%A9%84%E6%A6%84%E6%B1%89%E5%8C%96%22+%22-%E9%80%8F%E6%98%8E%E5%A3%B0%E5%BD%A9%22+-other%3Awebtoon%24+-uploader%3Aquanbuzhineng+-uploader%3ATMDlixin250+-uploader%3Aarchen+-uploader%3A%E6%AB%BB%E4%BA%95%E6%99%AF%E5%92%8C+-uploader%3A%E6%AE%8B%E6%9C%88%E4%B8%B6

### 问题是？

大佬 这个问题 接续 上一个 issues
https://github.com/hymbz/ComicReadScript/issues/179
我刚才发现 冲突的脚本了是这个
![image](https://github.com/user-attachments/assets/4fc4708d-f693-4c70-a94b-dc123ec93b63)
https://github.com/Meldo-Megimi/EH-Page-Scrobbler
这个脚本是 已经不存在的E站页码 重新 出现的 脚本
只要一激活这个脚本 画廊外的 缩略图评分就不好使了
这个能兼容一下嘛  求你了
没有页码 会死的。。 都不知道翻了多少页了 谢谢 辛苦大佬了

**Comment by hymbz** [comment]
已更新修复

**Comment by lhj5426** [comment]
感谢 已更新 确实可以了 谢谢 大佬
