### ISSUE TITLE
关闭自动进入阅读模式失效，在kemono关闭后仍会自动进入阅读模式

### ISSUE THREAD

**Issue by tamendeshijie** [hymbz/ComicReadScript#181]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

篡改猴

### 使用的浏览器是？

谷歌

### 问题会在哪个网页上出现？

https://kemono.su/posts

### 问题是？

进入kemono以及其他漫画网站时，会闪一下白色（应该是阅读模式），但是其他漫画网站不会出现问题，只有kemono,对于没有图片的网站，闪一下就恢复了，对于有图片的则会进入阅读模式

**Comment by tamendeshijie** [comment]
我是关闭了自动进入的，他仍然会自动进入阅读模式

**Comment by hymbz** [comment]
已更新修复
