### ISSUE TITLE
希望可以增加分数页码进度显示在角落

### ISSUE THREAD

**Issue by Thundercup** [hymbz/ComicReadScript#182]
### 具体描述

希望可以添加如图中这种样式的进度组件供选择
![image](https://github.com/user-attachments/assets/87c79ec6-a5d2-4ba8-a607-500f1d53aedf)

**Comment by hymbz** [comment]
相比滚动条有什么优点呢？现在只要鼠标滑到滚动条上或点一下中心区域也能看到具体的当前页数吧？

**Comment by Thundercup** [comment]
> 相比滚动条有什么优点呢？现在只要鼠标滑到滚动条上或点一下中心区域也能看到具体的当前页数吧？

这是始终显示的，而且搭配上时间很适合全屏观看时使用

**Comment by hymbz** [comment]
这种样式的进度只适用于单页显示的情况，脚本在双页、卷轴、并排卷轴模式下需要显示多个页数，还需要将显示方式改成对应的横向、竖向、多列竖向。加上感觉需要这个功能的人并不多，所以非常抱歉，暂不考虑实现该功能。
