### ISSUE TITLE
可乐漫画被屏蔽

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [hymbz/ComicReadScript#184]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

篡改猴

### 使用的浏览器是？

狐猴浏览器

### 问题会在哪个网页上出现？

https://www.colamanga.com/manga-ii42395/1/191.html

### 问题是？

我没有开广告拦截插件，但是还是显示广告被拦截弹窗，漫画就会显示null，应该是后面的漫画被挡住了，所以加载失败了
![Screenshot_20240828-185324](https://github.com/user-attachments/assets/7b7341d5-e2f2-427e-9c58-c197f39269bc)
![Screenshot_20240828-191134](https://github.com/user-attachments/assets/6441c934-877e-4b59-ab79-bb941f1e3882)
不知道能不能把广告拦截弹窗屏蔽掉😂

**Comment by SaltedFish-Extreme** [comment]
刚才用kiwi浏览器也是一样，把拦截广告的插件和屏蔽广告选项都关了也是这样😭漫画加载一两页就弹出来了，后面的都不能看了

**Comment by hymbz** [comment]
脚本在进入阅读模式后会隐藏原网页上的弹窗避免遮挡到漫画，可乐漫画应该就是检测到了这个才提示广告被拦截的。

只要随便安装些「uBlock Origin」之类的广告拦截插件就可以了，默认就会把这个功能也给屏蔽掉。

漫画显示 null 则是另一个 bug 导致的，已更新修复。

**Comment by SaltedFish-Extreme** [comment]
@hymbz 好的，感谢老哥了，没问题了😘
