### ISSUE TITLE
后续会出可以自己排序漫画页码的功能吗

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [hymbz/ComicReadScript#185]
### 具体描述

有的漫画上传的时候页码会乱，比如看漫画的[海贼王](https://www.manhuagui.com/comic/1128/771633.html) 第一页显示的其实是中间部分的漫画，应该是上传乱了，看到中间还要翻回来看这一页😂所以我想那个网格显示漫画的功能是不是也可以加一个拖拽排序漫画的功能😌

**Comment by hymbz** [comment]
遇到的概率实在是太低了，感觉没什么必要吧😂在漫画评论里说下或联系网站管理改过来更好

**Comment by SaltedFish-Extreme** [comment]
概率确实比较低，感觉是最近才有的，上次看一个漫画最新章节第一页也是乱了，过了半个月了也没改，可能也没人说吧😂
