### ISSUE TITLE
Manga translation always translates to Chinese (Simplified) regardless of Target language

### ISSUE THREAD

**Issue by ItsVovix** [hymbz/ComicReadScript#186]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

Violentmonkey

### 使用的浏览器是？

Firefox 132.0a1 / Chromium 127.0.6533.88

### 问题会在哪个网页上出现？

https://e-hentai.org/g/2555793/ec6edd2afc/

### 问题是？

Hello, I recently found this **amazing** script with translation capabilities. However, whenever I try to translate **ANY** manga using the translator it is always translated into Chinese (Simplified) ignoring my selection in Target language. I've tested different browsers, websites, languages and both Tampermonkey and Violentmonkey but nothing helped. When I use the web version of the translator (which doesn't use this extension) translating to English works as intended.
I know that English users are a minority when it comes to this script, but I'd be very happy if this issue were to be addressed!

Thank you.
<details>
  <summary>Using this extension</summary>

![Screenshot 2024-09-07 161625](https://github.com/user-attachments/assets/5d2a041f-682c-46dd-bbb9-834bc7fee077)
![Screenshot 2024-09-07 162014](https://github.com/user-attachments/assets/4c2b8a31-c2fb-4393-812a-1c1bc702a1c1)

</details>
<details>
<summary>Using the webpage</summary>

![Screenshot 2024-09-07 160720](https://github.com/user-attachments/assets/7a39909f-9b6c-4876-abd9-9c21c34603f4)
![Screenshot 2024-09-07 162155](https://github.com/user-attachments/assets/c04710b4-ef6a-494f-b625-8a8aca893918)
</details>

**Comment by hymbz** [comment]
Updated and fixed. 

Because I only tested using Chinese, I wasn't able to discover this bug😢, sorry.

**Comment by ItsVovix** [comment]
No problem! Thank you for such a quick fix.
But even after updating, I still unfortunately can't get it to work, using the selfhosted option still translates to Chinese only,,

**Comment by hymbz** [comment]
Have you confirmed that the script has been updated to the latest version?

![PixPin_2024-09-08_21-04-05](https://github.com/user-attachments/assets/afe72459-53eb-49f3-80c3-0214a52cd0ec)

**Comment by ItsVovix** [comment]
Yes, I made sure that the version is 9.7.5. I even tried to reinstall the script, both from here and from greasyfork, but sadly it didn't help. I also checked the code and it looks like the "fix" is there. Following [your guide](https://comic-read-docs.pages.dev/%E6%9C%AC%E5%9C%B0%E9%83%A8%E7%BD%B2%E7%BF%BB%E8%AF%91.html) on setting manga-image-translator in docker didn't help either,, (i tried it before as well but forgot to mention it)

So I'm absolutely clueless as to why it doesn't work :(
<details>
  <summary>Screenshots</summary>

![Screenshot 2024-09-08 192024](https://github.com/user-attachments/assets/8210ac4b-065d-4a28-89fe-a25eddfca637)
![Screenshot 2024-09-08 191842](https://github.com/user-attachments/assets/384bb6b5-cf1b-4fef-864a-471996428ffb)
![Screenshot 2024-09-08 192125](https://github.com/user-attachments/assets/5bccf4ab-8138-4693-8cc0-5bc32ae993b4)
![Screenshot 2024-09-08 192731](https://github.com/user-attachments/assets/e902cb07-9a51-4403-87db-9443d71c1d31)

</details>

**Comment by popcion** [comment]
you can try to add another command in docker-compose.yml
--target-lang ENG

**Comment by hymbz** [comment]
Updated and fixed.

it's because I didn't update manga-image-translator😂

https://github.com/zyddnys/manga-image-translator/commit/a925e22ce41cb99555313b0cb83e3731a7cb096c

**Comment by ItsVovix** [comment]
> you can try to add another command in docker-compose.yml --target-lang ENG

Unfortunately it seems that the --target-lang flag doesn't do anything in the web mode.
But thanks for the suggestion!

**Comment by ItsVovix** [comment]
> Updated and fixed.
> 
> it's because I didn't update manga-image-translator😂
> 
> [zyddnys/manga-image-translator@a925e22](https://github.com/zyddnys/manga-image-translator/commit/a925e22ce41cb99555313b0cb83e3731a7cb096c)

Haha, I'm glad the issue wasn't on my end, works like a charm now. Thanks again!
