### ISSUE TITLE
对于本地部署manga-image-translator的情况,翻译按钮增加可以选"翻译当前页"/"翻译全部图片"/"翻译当前页至结尾"或者快捷键可以配置

### ISSUE THREAD

**Issue by zmw0510git** [hymbz/ComicReadScript#188]
### 具体描述

对于本地部署manga-image-translator的情况,
a)翻译按钮增加可以选"翻译当前页"/"翻译全部图片"/"翻译当前页至结尾"三者其一的功能
或者
b)"翻译全部图片"和"翻译当前页至结尾"可以配置快捷键(现在只有"翻译当前页"的快捷键可配置)
再或者
c)设置一个开关,允许进入下一话时,继续"翻译全部图片"

因为"翻译全部图片"和"翻译当前页至结尾"现在的入口要
移动鼠标到"设置" 点击展开设置
移动鼠标到"翻译全部图片"或者"翻译当前页至结尾"再点击

现在很多漫画都是什么X.X,1话拆成好多话,没几页就要操作一次,有点繁琐...

**Comment by hymbz** [comment]
已更新实现最简单的 b 方案
