### ISSUE TITLE
漫画人（动漫屋）有时候会失效

### ISSUE THREAD

**Issue by 7sevenseven** [hymbz/ComicReadScript#19]

**Comment by hymbz** [comment]
已修复。

dm5 有时候域名会由 www.dm5.com 变为 tel.dm5.com，因为脚本是严格按域名匹配的所有就会失效，现在把 tel.dm5.com 也加进匹配项了。

**Comment by 7sevenseven** [comment]
> 
> 
> 已修复。
> 
> dm5 有时候域名会由 [www.dm5.com](http://www.dm5.com) 变为 tel.dm5.com，因为脚本是严格按域名匹配的所有就会失效，现在把 tel.dm5.com 也加进匹配项了。

感谢，修复的太快了

**Comment by liraqb** [comment]
> 已修复。
> 
> dm5 有时候域名会由 [www.dm5.com](http://www.dm5.com) 变为 [tel.dm5.com](tel.dm5.com)，因为脚本是严格按域名匹配的所有就会失效，现在把 [tel.dm5.com](tel.dm5.com) 也加进匹配项了。

在这个页面不起作用：[山海逆战漫画_515连载中_在线漫画_动漫屋 ](https://www.dm5.com/manhua-shanhainizhan1/)

另外【放大】和【简易漫画阅读模式】功能失效了。【放大】显示的区域不对，并且没有放大。【简易漫画阅读模式】点击没有反应。

浏览器：Cent Browser 4.1.7.182 (Chromium 78.0.3904.108)

**Comment by hymbz** [comment]
> > 已修复。
> > DM5 域名有时候会由 [www.dm5.com](http://www.dm5.com) 变为 [tel.dm5.com](tel.dm5.com)，因为脚本是严格按域名匹配的所有就会失效，把现在 [tel.dm5.com](tel.dm5.com) 也。加进匹配项了。
> 
> 在这个页面不起作用：[山海逆战漫画_515 连载中_在线漫画_动漫屋](https://www.dm5.com/manhua-shanhainizhan1/)
> 
> 另外【放大】和【简易漫画阅读模式】功能失效了。【放大】显示的区域不对，并且没有放大。【简易漫画阅读模式】单击没有反应。
> 
> 浏览器：美分浏览器 4.1.7.182（铬 78.0.3904.108）

已修复。
放大功能是我很早写的，当时没有考虑到多站点适配问题，因为我打算之后重构脚本，所以暂时就不修放大了，等之后重构再修。
简易漫画阅读模式失效具体是在哪个网站？

**Comment by liraqb** [comment]
>简易漫画阅读模式失效具体是在哪个网站？

[入间同学入魔了01话 - 西修 - 连载中 - 漫画粉](https://www.manhuafen.com/comic/2342/180625.html)（要在页面右边的`阅读设置`改为`上下滚动阅读`。）
[入间同学入魔了第01话在线观看-狂人漫画网](https://www.krmanhua.com/manhua/rujiantongxuerumole/474428.html)（要点击`下拉阅读`。）

**Comment by hymbz** [comment]
> > 简易漫画阅读模式失效具体是在哪个网站？
> 
> [入间同学入魔了 01 话 - 西修 - 连载中 - 漫画粉](https://www.manhuafen.com/comic/2342/180625.html)（要在页面右边的`阅读设置`改为`上下滚动阅读`。）
> [入间同学入魔了第 01 话在线观看 - 狂人漫画网](https://www.krmanhua.com/manhua/rujiantongxuerumole/474428.html)（要点击`下拉阅读`。）

这是 Feature 不是 Bug，简易漫画模式就只是简单的将当前页面的所有图片作为图片源，所以在这两个站点使用需要改为滚动阅读模式，让所有图片都显示出来才行。

**Comment by liraqb** [comment]
> 这是 Feature 不是 Bug，简易漫画模式就只是简单的将当前页面的所有图片作为图片源，所以在这两个站点使用需要改为滚动阅读模式，让所有图片都显示出来才行。

在改为滚动阅读模式后，仍然不能使用简易漫画阅读模式。这个功能可能失效了。

**Comment by hymbz** [comment]
> > 这是 Feature 不是 Bug，简易漫画模式就只是简单的将当前页面的所有图片作为图片源，所以在这两个站点使用需要改为滚动阅读模式，让所有图片都显示出来才行。
> 
> 在改为滚动阅读模式后，仍然不能使用简易漫画阅读模式。这个功能可能失效了。

(;´Д`) 确实是 Bug 了，上次没仔细测试非常抱歉，已经修复了。
