### ISSUE TITLE
Zero搬运网可以做支持么?

### ISSUE THREAD

**Issue by zmw0510git** [hymbz/ComicReadScript#190]
### 具体描述

Zero搬运网可以做支持么?
现在用简易模式,无法翻译
[网址发布点](https://zerobyw.github.io/)
这个站点一般是前面中文,然后没汉化就是日文

**Comment by hymbz** [comment]
无法翻译的 bug 已更新修复。

**Comment by zmw0510git** [comment]
感谢,测试OK
