### ISSUE TITLE
PWA报错：Cannot set property imgList of #<Object> which has only a getter

### ISSUE THREAD

**Issue by yunshaochu** [hymbz/ComicReadScript#191]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

Tampermonkey

### 使用的浏览器是？

EDGE 版本 127.0.2651.74 (正式版本) (64 位)

### 问题会在哪个网页上出现？

https://comic-read.pages.dev/

### 问题是？

具体情况：
一开始能正常打开图片，在看到"将本页面作为PWA应用安装到电脑上"的提示后就点击了确认安装，安装结束后就无法打开图片了，时间大约是下午3点。之后尝试卸载应用、更换浏览器都无法重新浏览图片。
网页无影响，仅PWA出现问题。

报错：
在用PWA打开本地图片，弹出以下错误，并且无法浏览图片：
index-6cnJEWbn.js:94  ComicRead Toast: Cannot set property imgList of #<Object> which has only a getter
ne.error @ index-6cnJEWbn.js:94
O @ index-6cnJEWbn.js:96
O.error @ index-6cnJEWbn.js:96
Yn @ index-6cnJEWbn.js:119
await in Yn
Px @ index-6cnJEWbn.js:120
index-6cnJEWbn.js:96  Uncaught (in promise) Error: Cannot set property imgList of #<Object> which has only a getter
    at O (index-6cnJEWbn.js:96:10496)
    at O.error (index-6cnJEWbn.js:96:10715)
    at Yn (index-6cnJEWbn.js:119:10027)
O @ index-6cnJEWbn.js:96
O.error @ index-6cnJEWbn.js:96
Yn @ index-6cnJEWbn.js:119

**Comment by smzwxy** [comment]
我也遇到了同样的问题，在本地使用ComicRead PWA时，再尝试将文件、文件夹、压缩包拖入ComicRead PWA时，提示了Cannot set property imgList of #<Object> which has only a getter的报错，卸载重新安装后问题依然存在。之前在电脑上使用ComicRead PWA时没有遇到这样的问题。
![image](https://github.com/user-attachments/assets/f15a1667-b966-4ff6-a1f9-a99bfd431fa4)

**Comment by hymbz** [comment]
已更新修复。如果还报错的话 `ctrl + F5` 刷新一下就好了。

**Comment by yunshaochu** [comment]
可以了(^o^)/
