### ISSUE TITLE
进入页面之后，无法通过插件获取frame里的图片。或者只能获取当前页面浏览的一张。获取不到其他。

### ISSUE THREAD

**Issue by capalens** [hymbz/ComicReadScript#192]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

Tampermonkey

### 使用的浏览器是？

chrome

### 问题会在哪个网页上出现？

https://www.postype.com/@toyaru/post/15102600

### 问题是？

在实例网站中，出现如下问题：

问题一：如果出现这种限制图片显示的Jsframe，那么经常无法进入插件的【简易阅读页面】。

问题二：https://www.postype.com/@dang-choi/post/15707866 这个网页，进入【简易阅读页面】之后，无法download所有frame中的图片。比如frame里有10张图，那么只能download到第一张或者第二张。类似的情况，比如这个帖子也是一样。https://www.postype.com/@khgfactory/post/17710925

即便是付费了图片，在本地通过浏览器能显示，也无法通过插件全部获取到本地。

问题三：这个网站现在提供的源是webp，虽然上传上去的图片格式不同，但是下载下来（破除网页限制后，右键存图也是webp格式）全部都是webp格式，希望图片下载后能自动保存成 .jpg .png 等比较常见的格式。

求大佬帮忙解决！感激不尽！

**Comment by hymbz** [comment]
这是因为网站使用了 swiper 来显示图片，并且开启了 Virtual Slides，只会渲染展示图片及其相邻的图片，其余未渲染的图片脚本就检测不到了。也找不到获取所有图片链接办法，所以非常抱歉没法支持这个网站😢

**Comment by capalens** [comment]
谢谢大佬，原来如此。这个网站的保护做得很好，大佬你的插件是我用的最好用插件，之前一直很依赖这个插件。但是以往这个网站的frame可以用，最近升级以后，估计应用了swiper，frame里的就没法下了。

不过这两天我试了试别的插件，发现有这个拓展居然可以突破你说的这个渲染限制。就是这个：https://chromewebstore.google.com/detail/image-downloader-imageye/agionbommeaifngbhincahgmoflcikhm?utm_source=ext_app_menu

还挺有趣的，不过这个拓展没有公开源码。提供一个思路，供大佬研究。


postype这个网站的图片，如果不应用swiper的话，图片下载还是没问题的。就是后缀名是webp。不知道这个大佬回头能不能帮忙调整一下后缀名的自动更改。

再次谢谢大佬。
