### ISSUE TITLE
漫画柜无法正常加载

### ISSUE THREAD

**Issue by alem0n** [hymbz/ComicReadScript#193]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

iPados stay

### 使用的浏览器是？

Safari

### 问题会在哪个网页上出现？

https://www.manhuagui.com/comic/33735/457511.html

### 问题是？

iPad Air3
iPadOS18.0

使用浏览器打开漫画柜的漫画就会一直刷新加载,并且会让系统卡死

**Comment by alem0n** [comment]
漫画柜有时候会加载出来但是大多数时候都有问题。拷贝漫画就可以正常使用

![IMG_0024](https://github.com/user-attachments/assets/52bc7d92-85bc-44d1-8b43-25ea5e10d558)

**Comment by hymbz** [comment]
一直刷新加载是说，一直在加载但加载不出来，还是说网页不断被刷新？

我手上的 iphone 无法复现这个 bug。感觉可能是和其他脚本或扩展冲突了？

**Comment by hymbz** [comment]
有安装其他脚本或扩展吗？有的话试试禁用以后还会不会这样

**Comment by alem0n** [comment]
找到了解决办法，在stay中选中这个脚本然后打开 不在内嵌iFrame中运行 就可以解决加载问题

![image](https://github.com/user-attachments/assets/80eb87be-ff53-459a-80d8-ae8ee1964faf)

![image](https://github.com/user-attachments/assets/f4534227-d453-4225-8a84-2b76c18865fd)
