### ISSUE TITLE
Zero搬运网最新版本无法正常翻译,回退旧版本v10.1.0正常

### ISSUE THREAD

**Issue by zmw0510git** [hymbz/ComicReadScript#195]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

Tampermonkey

### 使用的浏览器是？

Chrome

### 问题会在哪个网页上出现？

http://www.zerobywz.com/plugin.php?id=jameson_manhua&a=read&zjid=523934

### 问题是？

v10.1.1无法在Zero搬运网上无法弹出获取权限的窗口,按下翻译按钮后显示下载图片失败.
v10.1.0正常

**Comment by hymbz** [comment]
已更新修复

**Comment by zmw0510git** [comment]
> 已更新修复

更新到最新版本,故障依旧啊...

**Comment by zmw0510git** [comment]
![QQ20241005-150202](https://github.com/user-attachments/assets/15e31515-2dd8-4beb-8c78-16f0598724d3)
如上图所示

**Comment by hymbz** [comment]
更新了。

昨天我在 violentmonkey 上测试发现有报错，以为就这一个问题改了就完了，没想到用 Tampermonkey 时还有个问题😂

**Comment by zmw0510git** [comment]
问题已解决,谢谢
