### ISSUE TITLE
e站无法加载

### ISSUE THREAD

**Issue by manran000** [hymbz/ComicReadScript#198]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

tampermonkey

### 使用的浏览器是？

edge

### 问题会在哪个网页上出现？

https://exhentai.org/g/3101504/642280aa49/

### 问题是？

e站无法加载图片了

**Comment by winoros** [comment]
ex里站的 api 更新了？其他的 Android app 也寄了

**Comment by hymbz** [comment]
> ex里站的 api 更新了？其他的 Android app 也寄了

<https://forums.e-hentai.org/index.php?s=&showtopic=199743&view=findpost&p=6559928>

<https://forums.e-hentai.org/index.php?showtopic=244935>

更新了缩略图的显示，现在可以同时显示页码和文件名了。表站之后应该也会更新吧。

**Comment by hymbz** [comment]
已更新修复
