### ISSUE TITLE
请求适配ipad的userscripts

### ISSUE THREAD

**Issue by tamendeshijie** [hymbz/ComicReadScript#200]
### 具体描述

目前在ipad上安装safari的userscripts插件后，安装阅读器并不能正常使用

**Comment by tamendeshijie** [comment]
在stay上似乎并没有运行（还有一款叫做图片全载的插件倒是可以使用），我的是ipad mini4，系统比较老是15.0

**Comment by hymbz** [comment]
版本太旧导致的，Safari 在 16.4 版本后才支持正则的[后行断言](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Lookbehind_assertion)。

不过脚本很多地方都用到了后行断言改起来比较麻烦，而且旧版本的兼容问题可能还不止这一个，所以非常抱歉没法修复😢
