### ISSUE TITLE
拷貝漫畫部分漫畫目錄隱藏了

### ISSUE THREAD

**Issue by leadra** [hymbz/ComicReadScript#202]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

Violentmonkey

### 使用的浏览器是？

Cent Browser版本 5.1.1130.129 (正式版本) (64 位元) (Portable) (Chromium 118.0.5993.159)

### 问题会在哪个网页上出现？

https://mangacopy.com/comic/yueguangxiadeyishijiezhilv

### 问题是？

https://mangacopy.com/comic/yueguangxiadeyishijiezhilv
月光下的異世界之旅
目前有些漫畫，最新更新點進去都看不到，有些則是目錄都消失
書架的只能看最新的連結
暫時利用拷贝漫画增强的閱讀紀錄，點進去後有目錄來跳，雖然只有吐槽，但是ComicRead就能載入圖片
(雖然也有點好奇留言的大家怎麼看到的)

![image](https://github.com/user-attachments/assets/800cd633-683c-4454-9e6b-1aebd31bc0ff)
![image](https://github.com/user-attachments/assets/0a53984b-3e22-47dc-b521-1433d6a141ec)
![image](https://github.com/user-attachments/assets/0680b4db-56ce-4d73-a483-51415f36da8d)

**Comment by leadra** [comment]
非常感謝!
我用PC開的
似乎是因為最近有人狂攻擊拷貝的關係?
    axios.get('https://api.mangacopy.com/api/v3/comic/' + comic + '/chapter/' + chapter)
之前腳本內自己改域名總有一個可以看
mangacopy.com
copymanga.tv
現在沒辦法了，沒有尋找能力@@"
感謝能修復

**Comment by leadra** [comment]
不好意思，想詢問這本[百華荘](https://mangacopy.com/comic/Hyakkasou)
還有在更新，所以書架自己跑出來

目錄無法出現，是不是只有APP才看的到?
直接點話數進去有評論區，不過沒法讀取圖片，1-13都是
![image](https://github.com/user-attachments/assets/bb42e5c0-70f6-4b2f-8ffd-58f3c654c8c9)
![image](https://github.com/user-attachments/assets/53235aeb-bdaf-4a52-bf7e-aeb8880e2eb0)
![image](https://github.com/user-attachments/assets/3ea0ca40-71e5-4ff7-8d45-701558b1dd33)
![image](https://github.com/user-attachments/assets/e94ea20f-d692-49a6-9ecd-98d92a0c84a7)

https://mangacopy.com/comic/Hyakkasou
https://mangacopy.com/comic/Hyakkasou/chapter/f8380047bece11ef9bchttps://mangacopy.com/comic/Hyakkasou/chapter/f8380047bece11ef9bc63f487b7d9a9a63f487b7d9a9a

**Comment by hymbz** [comment]
> 不好意思，想詢問這本[百華荘](https://mangacopy.com/comic/Hyakkasou) 還有在更新，所以書架自己跑出來
> 
> 目錄無法出現，是不是只有APP才看的到? 直接點話數進去有評論區，不過沒法讀取圖片，1-13都是

目录的接口倒是还能用，不过获取图片的接口会直接提示漫画不存在，搜了下其他第三方软件好像也都没有办法，这我就无能为力了😥

不过倒是搜索到了疑似拷贝里站的「[热辣漫画](https://www.relamanhua.org)」，直接将拷贝漫画网址里的域名替换成 `www.relamanhua.org` 就可以跳转过去。看到有人说拷贝漫画首页有这个网站的推荐，加上网址可以无缝替换，应该是使用的相同的服务器数据。唯一问题就是热辣漫画很多漫画都要付费。。

下次更新会为「百華荘」这种直接404的漫画加上目录，顺便在无法加载图片时加个跳转到热辣漫画的链接。

**Comment by hymbz** [comment]
不对，又想了想。还是不加热辣漫画的跳转了，毕竟是要付费的网站。正确的做法应该是直接去其他网站搜索。

**Comment by leadra** [comment]
你說的也對..看來是後來拷貝為了賺錢分開的，倒是沒想到書架也是共用的@@"
自己再去E看好了，感謝~
