### ISSUE TITLE
識別廣告頁會蓋到一般圖片

### ISSUE THREAD

**Issue by leadra** [hymbz/ComicReadScript#203]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

Violentmonkey

### 使用的浏览器是？

Cent Browser版本 5.1.1130.129 (正式版本) (64 位元) (Portable) (Chromium 118.0.5993.159)

### 问题会在哪个网页上出现？

https://e-hentai.org/g/3132007/dad75a3450/

### 问题是？

辛苦了
目前eh和exh都測試過，廣告偵測會往前覆蓋到正常圖片
顯示黃條，無法載入圖片，關閉偵測就可以全部顯示
https://e-hentai.org/g/3132007/dad75a3450/
https://exhentai.org/g/3132007/dad75a3450/

![image](https://github.com/user-attachments/assets/7ae17493-4091-4e55-829b-9f764d3ca8e0)
![XX01](https://github.com/user-attachments/assets/8084a02c-b9d1-4ac3-80ee-80af0be61401)

**Comment by hymbz** [comment]
感谢反馈，已更新修复。

这个 bug 需要页数多到分页才能触发，我因为缩略图行数设为了 40 需要两百以上的页数才能分页，所以前几天有人报告这个 bug 时我找了一圈都没能复现还以为只是个例的识别错误导致的😂，多亏了你给出了具体的链接。

**Comment by leadra** [comment]
原來如此，不過我這個只有35P，真虧能發現ww
我還是用廣告的tag去找

感謝更新!!

**Comment by leadra** [comment]
https://e-hentai.org/g/3133586/11b30186f9/
https://exhentai.org/g/3133586/11b30186f9/

https://exhentai.org/g/3134903/929ab17a81/
不好意思，關於cent瀏覽器，在這2個畫廊，還是會有這個問題
而且即使不會覆蓋到一般圖片，廣告頁仍然會顯示載入-黃色
![image](https://github.com/user-attachments/assets/086ab060-a25d-40ce-952b-14952349fab3)

我測試chrome看是正常顯示的
如果是瀏覽器版本問題的話就算了

**Comment by hymbz** [comment]
我这边测试没法复现，确定脚本更新到最新版了吗？

**Comment by leadra** [comment]
不好意思ㄚㄚ~
後來我發現，是我更新腳本時，他快取cache還是抓上一版本，後來檢查腳本發現，我就趕快刪除留言了，真是抱歉
