### ISSUE TITLE
求增加一个换页动画。

### ISSUE THREAD

**Issue by bigbenbird** [hymbz/ComicReadScript#207]
### 具体描述

之前一直在用 https://greasyfork.org/zh-CN/scripts/421371-%E6%8B%B7%E8%B4%9D%E6%BC%AB%E7%94%BB%E5%A2%9E%E5%BC%BA 这个插件来看拷贝漫画。

但是因为现在拷贝漫画隐藏了，所以被人推荐使用这个，果然可以看隐藏漫画，总体功能也比 上面的老script要好。

但是现在的这个插件，在双页模式下，换页时候，没有换页动画，切换的时候，会有一点突兀，如果可以给插件增加一个换页动画，那就完美了。

**Comment by hymbz** [comment]
这个非常抱歉，因为脚本实现方式的缘故要加过渡动画非常麻烦，所以目前暂不考虑实现😢

而且双页模式下使用上下滑动的动画会有种翻考卷的感觉怪怪的（个人感受），具体你可以用鼠标快速拖拽滑动页面来翻页试试看，上下/左右两种方向都可以试试。

或者可以等之后更新的卷轴模式下的双页模式，体验应该也差不多。

**Comment by hymbz** [comment]
久等了，现在脚本支持翻页动画了，给「设置」-「外观」-「翻页动画时长」设上一个大于0的数，就可以有翻页动画了。
