### ISSUE TITLE
图片被分割为若干部分，且从下向上倒序显示

### ISSUE THREAD

**Issue by Yu-Haoyang** [hymbz/ComicReadScript#208]
### 在提交 issue 之前，请先确认

- [X] 脚本已更新至最新版本

### 使用的油猴扩展是？

Tampermonkey（篡改猴）

### 使用的浏览器是？

Chrome

### 问题会在哪个网页上出现？

18comic.vip

### 问题是？

![MK37~`O@38)0$SG)J(W6QL6](https://github.com/user-attachments/assets/ab1d2274-fa80-4161-a618-cff92bf4005d)
如图，漫画的每一页都被分割为几部分，显示为向下而上的倒序显示。

**Comment by hymbz** [comment]
我这边试了几个都还是正常的，应该只是部分漫画会出现这种问题？截图这个漫画的网址是多少？

**Comment by Yu-Haoyang** [comment]
> 我这边试了几个都还是正常的，应该只是部分漫画会出现这种问题？截图这个漫画的网址是多少？

https://18comic.vip/photo/572049

**Comment by hymbz** [comment]
感谢反馈，已更新修复。
