### ISSUE TITLE
能否添加一下全屏功能

### ISSUE THREAD

**Issue by heroxv** [hymbz/ComicReadScript#209]
### 具体描述

![Screenshot_2024-12-22-02-49-45-411_com microsoft emmx](https://github.com/user-attachments/assets/c8504651-c462-42e6-8f7a-2e075b591c2f)
平板电脑状态下这样看下去，字体还是有点稍小。
![Screenshot_2024-12-22-02-50-30-960_com microsoft emmx](https://github.com/user-attachments/assets/f2527b09-dc29-47d1-bdd8-ab544264680f)
这样看起来就可以了。
另外可以设置一下夜间模式随系统吗。

**Comment by hymbz** [comment]
已更新加上了全屏按钮。

不过夜间模式跟随系统感觉没什么必要吧，因为会影响到背景色，平时一般也不会需要经常切换吧。即使是移动设备，因为背景占比更小的原因，即使开启了夜间模式，因为漫画背景是白色的，屏幕也还是会很亮吧。
