### ISSUE TITLE
反和谐一下dmzj的作者页面吧

### ISSUE THREAD

**Issue by heroboy** [hymbz/ComicReadScript#22]
例如: https://manhua.dmzj.com/tags/gthr.shtml

**Comment by hymbz** [comment]
这个暂时还无能为力呢(´ー`)，漫画那边有接口能拿到数据，但作者这边好像没有能拿到隐藏漫画数据的接口。如果之后能找到接口的话就能加上这个功能了。

**Comment by heroboy** [comment]
hi @hymbz , rss好像能拿到一点：http://manhua.dmzj.com/tags/g/gthr/rss.xml

**Comment by heroboy** [comment]
可以了
