### ISSUE TITLE
dmzj不能用了

### ISSUE THREAD

**Issue by s4028600** [hymbz/ComicReadScript#23]
無法阅读被封漫画
之前還可以
突然失效了

**Comment by dcd556** [comment]
+1，同这种情况

**Comment by hymbz** [comment]
之前的接口挂了，拿不到隐藏漫画的数据了，不过数据倒是还在。接口现在好像时晚上八点开放，早八点关闭。总之希望只是暂时的技术性调整吧。

**Comment by s4028600** [comment]
好像不是早8点关闭
6点以前好像就关闭了
不确定确切时间
