### ISSUE TITLE
dmzj被封漫画无法使用

### ISSUE THREAD

**Issue by cjh1993927** [hymbz/ComicReadScript#24]
您好，dmzj被封漫画好像无法观看了，会卡在正在加载页面。

**Comment by GrandArth** [comment]
似乎是接口会每天定时关闭导致的, 除非有别的接口, 不然作者也无能为力吧.

**Comment by hymbz** [comment]
> 您好，dmzj 被封漫画好像无法观看了，会卡在正在加载页面。

回复晚了抱歉，dmzj 被封漫画每晚八点到第二天六点可以看，其他时间接口关闭我也爱莫能助(´ー`)。
