### ISSUE TITLE
dmzj 切换章节方向错误

### ISSUE THREAD

**Issue by Aceralon** [hymbz/ComicReadScript#25]
dmzj在非卷轴模式下到最后一页后，如果点击方向下键或者方向右键，会跳转到上一章节而不是下一章节；内页中按方向左键无论是否第一页，都会提示跳转到上一章节。

**Comment by hymbz** [comment]
已修复。

> 按方向左键无论是否第一页，都会提示跳转到上一章节
这是 dmzj 的功能，因为不是非常影响用户体验，而且想说油猴脚本应该尽量不去修改原网站的功能，所以就没做处理。
