### ISSUE TITLE
nhentai上将脚本运用在单行本上效果不好

### ISSUE THREAD

**Issue by Thundercup** [hymbz/ComicReadScript#27]
目前发现脚本在nhentai上加载页数较多的单行本每次只能加载40页左右，刷新后才能继续加载，且在一百多页时无法继续加载。还有nhentai上阅读页数较多的漫画，右边会显示大量选页圆点，影响阅读体验

**Comment by hymbz** [comment]
加载问题已修复。

右边的圆点可以通过左侧边栏「阅读进度」按钮关掉。
