### ISSUE TITLE
ehentai的「Load comic」失效

### ISSUE THREAD

**Issue by liraqb** [hymbz/ComicReadScript#29]
在ehentai，「Load comic」失效，包括标签栏nhentai的「Load comic」

**Comment by hymbz** [comment]
失效是说点击后没有反应？我这边测试可以正常使用。你使用的是什么浏览器？脚本更新到最新了吧，另外也有可能是和其他脚本或插件冲突了

**Comment by liraqb** [comment]
版本：ComicRead 3.6
浏览器：Cent Browser 4.2.10.171（正式版本） （64 位） (portable) (Chromium 80.0.3987.163)

分别测试了插件和脚本的冲突问题，没有冲突。脚本已检测更新，没有更新。

**Comment by 123hundun123** [comment]
Cent Browser：版本 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)
ComicRead 版本：3.6
测试ehentai和nhentai的Load comic功能一切正常，请检查自己的配置

**Comment by liraqb** [comment]
> Cent Browser：版本 4.2.10.171（正式版本） （64 位） (Chromium 80.0.3987.163)
> ComicRead 版本：3.6
> 测试ehentai和nhentai的Load comic功能一切正常，请检查自己的配置

好吧，谢谢提醒，我又去测试了一下，我的配置应该没有问题，因为我在新浏览器上只安装了扩展程序Tampermonkey、Proxy SwitchyOmega，以及脚本ComicRead。我也试过了Google Chrome 81.0.4044.138（正式版本） （32 位）便携版，同样有问题。在nhentai.net上，「Load comic」没有问题。

**Comment by hymbz** [comment]
会不会是网络的原因？直接打开 ehentai 上漫画的单页可以正常显示吗？
也不是网络原因的话，按 F12 看看开发者工具里的 Console 下有没有报错信息，有的话贴上来

**Comment by liraqb** [comment]
图片加载正常，网络没有问题。

点击「Load comic」后，Console报错：

![](https://user-images.githubusercontent.com/62490653/83092322-a4190900-a0cf-11ea-8618-1bbf7f0c34b2.png)

![](https://user-images.githubusercontent.com/62490653/83092327-a54a3600-a0cf-11ea-9f55-b9718c606209.png)

点击nhentai的「Load comic」后，Console报错：

![](https://user-images.githubusercontent.com/62490653/83092329-a713f980-a0cf-11ea-87ae-0af91b8b9258.png)

**Comment by hymbz** [comment]
找出原因了，ehentai 的图片加载不了是因为你没有登录，具体原因我还在排查中，有点奇怪。nhentai 的图片加载不了是因为 nhentai 加了防盗链机制，脚本更新完就能正常加载了。

**Comment by laniidae** [comment]
e-hentai 点击 load 按钮报错, 已登录, 正常方式可以浏览图片
![image](https://user-images.githubusercontent.com/31888615/126525874-89cb28d9-6be4-422e-a2fe-122b38b008e5.png)

**Comment by hymbz** [comment]
> e-hentai 点击 load 按钮报错，已登录，正常方式可以浏览图片
> ![image](https://user-images.githubusercontent.com/31888615/126525874-89cb28d9-6be4-422e-a2fe-122b38b008e5.png)

脚本已更新修复。
