### ISSUE TITLE
呃，请问一下现在脚本是怎么用？

### ISSUE THREAD

**Issue by shinji-ikari** [hymbz/ComicReadScript#3]
忘了怎么安装上的脚本了，总之现在的脚本怎么用有点懵，点开 DMZJScript 然后点.js进去直接点RAW把内容都复制到暴力猴里面新建脚本提示出错。请问一下现在是怎么用....？

**Comment by hymbz** [comment]
现在各个站点的脚本合并为了一个，就是根目录下的 ComicRead.user.js，DMZJScript 可以直接删了装现在的 ComicRead，要装的话可以直接去[greasyfork](https://greasyfork.org/zh-CN/scripts/374903-comicread)装。带 RAW 的文件是未处理的方便 coding 用的，直接用会出错。

**Comment by shinji-ikari** [comment]
哦哦，明白了。抱歉了，因为蒙了搞不清楚该怎么用。Thanks♪(･ω･)ﾉ

**Comment by shinji-ikari** [comment]
感觉好像对DMZJ没用？安装了greasyfork里面的comicread，挑了个被屏蔽漫画，毫无反应一样，随便点个漫画进去也没跟使用DMZJScript时一样变成黑色的界面。
用的浏览器是firefox 52. + tampermonkey

**Comment by shinji-ikari** [comment]
hmmm，测试了一下油猴子，也是不行，因为没删掉DMZJSCRIPT,重新启用了一下。没问题。_(:з」∠) _

**Comment by hymbz** [comment]
那现在没问题了吧(｀･ω･)。火狐我用的63版，我这边测试是没问题，脚本因为用了 tampermonkey 的 API 所以用其他插件可能会出错(´_ゝ`)

**Comment by shinji-ikari** [comment]
ComicReadScript/ComicRead.user.js
重新装了几次试试看，没反应。GITHUB跟greasyfork的都试过，一个样。
firefox 52+tampermonkey插件。
纳闷的是dmzjscript的脚本还是能正常用。
囧了，刚才拿最新版的chrome+tampermonkey测试了一下。comicread在chrome上面反倒是没问题....能正常看到“漫画阅读脚本设置”。
firefox52跟63有什么很大的差别么？hmmm，总之Thanks♪(･ω･)ﾉ~脚本很好用。因为一些插件的原因firefox不能更新上去，不过dmzjscript正常用。真有什么必要的开chrome算了。
3Q

**Comment by hymbz** [comment]
找到原因了ﾟ∀ﾟ)ノ。是脚本384行`ScriptMenu.UserSetting = { ...defaultUserSetting, ...ScriptMenu.UserSetting };`的问题，火狐从55开始才支持对象的扩展运算符。把这行改成`ScriptMenu.UserSetting = Object.assign(defaultUserSetting, ScriptMenu.UserSetting);`就行了(`ヮ´)

**Comment by shinji-ikari** [comment]
....夭寿咯。真的解决了。感谢大大不辞辛苦的翻查。
