### ISSUE TITLE
放大功能异常以及漫画柜的异常

### ISSUE THREAD

**Issue by shinji-ikari** [hymbz/ComicReadScript#30]
浏览器: 火狐最新版 76.0.1 (64 位)
脚本扩展: tampermonkey
异常网站: dmzj (http://manhua.dmzj.com/wulimofashimaxiu/100205.shtml ) 随便哪个漫画都行
异常的功能: 放大
具体异常: 加载完成进入观看之后, 双击图片任意部分都可以打开放大功能,但是放大出来的有问题, 放大框里显示出来的不是虚线方框指向的图片部分, 基本上是黑色, 左右移动的话能调整到放大框显示出图片的一部分,但是也不是放大的,而是跟图片某个部分完全一样大小的.

异常网站: manhuagui , 随便哪个漫画
异常功能: 加载进入观看时, 加载时没问题.但是加载完成后,一定是加载所有图片完成之后,偶尔出现图片卡在该话的最后一个图片.并且本应该出现的观看模式也没了.(就是没开脚本进去的那样子), 观看模式没了也没办法上下滚动或者点击或右击 . 如果用键盘的方向键上下按一下的又重新显示观看模式.

两个问题都是从之前好几个版本就一直如此.一直忘了来反馈.ε=(´ο｀*)))

**Comment by hymbz** [comment]
放大功能因为修起来比较麻烦，而且我现在正在重构脚本，新版会用其他方式实现放大功能，所以现在旧版的就不修了。

漫画柜的 Bug 大概和脚本的实现方式有关，因为无法稳定复现所以也无法排查无法修复，等之后脚本重构后大概就不会复发了。
