### ISSUE TITLE
nhentai.net的loadcomic失效

### ISSUE THREAD

**Issue by MR-LHM** [hymbz/ComicReadScript#31]
点击loadcomic。图片无法加载。控制台打印
https://i.nhentai.net/galleries/1658890/4.undefined 
推测是图片类型获取失败。
gallery.images.pages 没有 t 字段的样子。
我改成
1592 const fileType = {
  jpg: 'jpg',
  png: 'png',
  gif: 'gif',
};
1619 const src = `https://i.nhentai.net/galleries/${gallery.media_id}/${i + 1}.${fileType[gallery.images.pages[i].extension]}`;
就能顺利运行

**Comment by hymbz** [comment]
已修复。
