### ISSUE TITLE
最近dmzj出问题，脚本又失效了

### ISSUE THREAD

**Issue by Kaorinomikan** [hymbz/ComicReadScript#35]
作者页读不出加*的作品，作品实际阅读无法进入阅读模式。
参考：
https://manhua.dmzj.com/diyumoshixihuansutongyouxidewanjiazaifeishedingyis/109415.shtml
https://manhua.dmzj.com/diyumoshixihuansutongyouxidewanjiazaifeishedingyis/
https://manhua.dmzj.com/tags/tietianyuaner.shtml

![image](https://user-images.githubusercontent.com/59602908/96253746-b942f580-0fe6-11eb-9234-50f29c8edc30.png)
![image](https://user-images.githubusercontent.com/59602908/96253765-c4962100-0fe6-11eb-90f1-2d28ffa39990.png)
![image](https://user-images.githubusercontent.com/59602908/96253776-c8c23e80-0fe6-11eb-8b81-cfb75d9fe56a.png)

**Comment by hymbz** [comment]
已修复
