### ISSUE TITLE
dmzj的下一章跟上一章按钮又丢了?

### ISSUE THREAD

**Issue by shinji-ikari** [hymbz/ComicReadScript#36]
之前刚出现DMZJ1.com的时候也出现过一次这毛病,之后小更新了一下好了.但是今天发现又来了这毛病.
PC端, firefox 81.02.2 , WIN7.
脚本最新版本. 扩展是tampermonkey.

链接: http://manhua.dmzj1.com/shangbanzuzhuanshengyishijiedangshanglesitianwangb/

**Comment by shinji-ikari** [comment]
![5{0G6LQI)@9VCCE2W_F YWH](https://user-images.githubusercontent.com/12407493/96377391-0aeeaa00-11b8-11eb-9754-06a6c6adfd8d.png)
![UJ0~6M_ @JNX(RGD(}SG9SI](https://user-images.githubusercontent.com/12407493/96377393-0d510400-11b8-11eb-99e8-b61a961a00d7.png)

这是退出界面后的对比截图

**Comment by hymbz** [comment]
把网址里的 dmzj1 改为 dmzj 就行了。因为感觉 dmzj1 只是技术性调整的临时域名，所以并不打算支持该域名。

**Comment by shinji-ikari** [comment]
囧了.明白了.3Q
