### ISSUE TITLE
漫画柜被封IP

### ISSUE THREAD

**Issue by baldandbrave** [hymbz/ComicReadScript#37]
在漫画柜使用脚本会一次性下载所有图片，遇到页数多的一章（例如单行本）会触发漫画柜请求限制ban掉IP。
能否限制为根据浏览进度异步加载图片？（如每次只加载8张）

相关代码段
https://github.com/hymbz/ComicReadScript/blob/master/ComicReadRaw.js#L173-L192

环境
TamperMonkey v4.11
ComicRead 4.3
Chrome 86.0.4240.183

**Comment by hymbz** [comment]
久 等 了，新版更新后现在脚本默认只会加载当前页数附近一定范围的图片。
