### ISSUE TITLE
dmzj1的下一章跟上一章按钮不存在? 我又来了_(:з」∠)_

### ISSUE THREAD

**Issue by shinji-ikari** [hymbz/ComicReadScript#39]
https://github.com/hymbz/ComicReadScript/issues/36
还是跟上次的一样,域名改成了DMZJ1.COM....
为什么还来汇报这个呢? 
因为dmzj.com 的域名直接403了. 带个1的反而还活着.大佬是不是考虑一下下?  (。﹏。) 

另外dmzj1.com还有个问题, 读页会有异常, 只显示几页然后就是 读取中的那个图片 在跳, 不过点了END退出脚本的漫画框模式之后.发现 网页上的全图都在.没有问题.

外加....现在dmzj.com的总是会出现 IP LIMIT导致打不开.测试了一下dmzj1.com反而不会.也是搞不清楚大妈之家在干嘛.

**Comment by shinji-ikari** [comment]
另外dmzj1.com还有个问题, 读页会有异常, 只显示几页然后就是 读取中的那个图片 在跳, 不过点了END退出脚本的漫画框模式之后.发现 网页上的全图都在.没有问题.

**Comment by hymbz** [comment]
看来是又在技术性调整了，参考上次应该过几天就好了。不过因为这段时间事太多我没什么空，就不更新脚本支持 dmzj1 了，抱歉(´_ゝ`)，等之后 dmzj 恢复吧

**Comment by shinji-ikari** [comment]
好的,主要是.最近一整段时间感觉DMZJ都不太对劲,总是有事没事 IP LIMIT, 打不开.这次直接403 _(:з」∠)_ 
那就先结了,没空也是没办法的.
