### ISSUE TITLE
能否加入图片不缩放选项？

### ISSUE THREAD

**Issue by blass0009** [hymbz/ComicReadScript#41]
有的漫画图片本身足够清晰，但是在双页阅读模式中，被缩放之后，常规ppi显示器上显示反而会变得模糊
例如800高的图片被拉伸到1080高，1200高的图片被拉伸到1440高
希望可以增加“不缩放”选项，不论浏览器窗口是否大于图片尺寸，均不对图片进行缩放，让图片以原尺寸显示

**Comment by hymbz** [comment]
感谢建议，会在之后的新版本中增加该功能的。
