### ISSUE TITLE
脚本被greasyfork删除

### ISSUE THREAD

**Issue by tio-plato** [hymbz/ComicReadScript#42]
刚才更新提示脚本已被从greasyfork移除，请问是被ban了还是主动下架了？

**Comment by blass0009** [comment]
借楼说一下，现在暂时可以通过点击
https://github.com/hymbz/ComicReadScript/blob/master/ComicRead.user.js
页面代码部分右上角的“RAW”按钮重新安装脚本。

**Comment by hymbz** [comment]
因为代码中引用了外部库的压缩后的代码所以被用「Minified code」理由举报了，我 chrome 的 gmail 扩展不知道什么时候莫名退出了登录状态导致我没看到通知的邮件Orz

**Comment by hymbz** [comment]
已恢复。
