### ISSUE TITLE
拷贝漫画

### ISSUE THREAD

**Issue by yebing233** [hymbz/ComicReadScript#44]
copymanga.com 拷贝漫画进入简易漫画模式无法加载图片
图：https://s3.bmp.ovh/imgs/2021/11/fe1cadd566d8b400.png
copymanga.net   这个进入简易漫画模式只能加载已经被加载的图片的页数
图：https://s3.bmp.ovh/imgs/2021/11/ad88c688f64ef60e.png

**Comment by hymbz** [comment]
删掉脚本再重装一下试试？脚本在7.25的更新后就已经支持拷贝漫画了，应该是会自动加载不需要用简易漫画模式，也进不去才对，可能是之前存的数据导致的 bug。

**Comment by yebing233** [comment]
> 删掉脚本再重装一下试试？脚本在7.25的更新后就已经支持拷贝漫画了，应该是会自动加载不需要用简易漫画模式，也进不去才对，可能是之前存的数据导致的 bug。

删掉后重新安装还是一样，是因为我是移动运营商吗
.com那个域名是自动进入漫画模式
.net的域名是要手动进入

**Comment by hymbz** [comment]
> 删掉后重新安装还是一样，是因为我是移动运营商吗 .com 那个域名是自动进入漫画模式 .net 的域名是要手动进入

那进到 Tampermonkey 的管理面板，点开脚本的详情页，切换到存储的标签页。这里是脚本存储数据的地方，把里面带有 copymanga 字样的几行删掉，或者直接全部删掉只留"{}"两个大括号。

简易模式相关的数据都是存在这里的，可能是删掉脚本时扩展还缓存着数据？所以重装后数据没有被重置？我这边试了两个域名都没问题，都可以自动进入漫画模式

**Comment by yebing233** [comment]
按照你说的方法试过了，可以自动进入漫画模式了
但是图片加载不出来
不进漫画模式图片能正常显示

**Comment by hymbz** [comment]
加载不出来是说，显示蓝色的加载中的图片吗？

**Comment by yebing233** [comment]
https://ibb.co/3TyKBfX     这是图床链接
就图上这样
应该是属于图裂吧

**Comment by hymbz** [comment]
在这个页面下按F12打开开发者工具，切换到 Console 标签页下，在「>」旁边的输入栏复制粘贴代码 `JSON.stringify([...document.querySelectorAll('#comicShow img')].map(e=>e.src))`，回车运行。这样会输出所有图片的地址，截图我看看。

https://ibb.co/8rgfrm1 这是我的输出

**Comment by yebing233** [comment]
https://ibb.co/Pc4sHnZ
这样吗

**Comment by yebing233** [comment]
就是这样 https://ibb.co/Jnpd7xv  他正常显示 
进了漫画模式就这样裂图  https://ibb.co/3TyKBfX
然后我刚刚挂代理进漫画模式他就刷出来图了  https://ibb.co/1Zm3rRD
不知道为什么
应该就是我移动运营商的问题吧

**Comment by yebing233** [comment]
麻烦你了

**Comment by hymbz** [comment]
不会，举手之劳罢了(ゝ∀･)
