### ISSUE TITLE
manhuacat使用时会滚动条会随机乱跳

### ISSUE THREAD

**Issue by beautifulword** [hymbz/ComicReadScript#45]
如题，在漫画猫使用阅读模式卷轴模式时，一旦滚动页面，滚动条会随机跳跃而不能一页一页的翻。

**Comment by hymbz** [comment]
已更新修复。

随机跳跃是因为脚本在加载完一张图片后会重新渲染一下组件，加载速度比较快的话就不会触发这个 bug 了。

**Comment by beautifulword** [comment]
> 已更新修复。
> 
> 随机跳跃是因为脚本在加载完一张图片后会重新渲染一下组件，加载速度比较快的话就不会触发这个 bug 了。

多谢大佬(*^▽^*)
