### ISSUE TITLE
nhentai自动翻页、彻底屏蔽漫画失效。

### ISSUE THREAD

**Issue by XavierLee-0** [hymbz/ComicReadScript#47]
![image](https://user-images.githubusercontent.com/63280021/142586263-46db7909-0746-482f-88d7-2dfce1d1d02a.png)
![image](https://user-images.githubusercontent.com/63280021/142586345-4b237763-2619-486b-8a67-0e2530dc4c9b.png)

**Comment by hymbz** [comment]
已更新修复。

我这边测试时不知道为什么可以直接访问变量 n，只是值为 undefinede 而已，不会报 n is not defined 的错。。。

**Comment by XavierLee-0** [comment]
更新之后就正常了。谢谢开发者。
