### ISSUE TITLE
漫画猫阅读模式点下一话页面404

### ISSUE THREAD

**Issue by beautifulword** [hymbz/ComicReadScript#48]
![image](https://user-images.githubusercontent.com/35883958/144816370-8996ba72-d11b-4d38-9006-e4718701096a.png)
如图，能请开发者修复一下吗

**Comment by hymbz** [comment]
是《血之辙》没错吧，能说下是具体哪一话出的问题吗？我这里没法复现。
另外看地址栏，是把应该被调用的函数转成了字符串导致的 Bug，但我看了好几遍代码也想不出可能的原因(´_ゝ`)
感觉代码正常执行的话应该是不会出现这种情况的，但要说是和其他浏览器扩展或脚本冲突也不至于出现这种情况，而且看截图你是切到无痕模式确保了没有冲突的对吧
总之就挺怪的，能再多提供一些信息吗？比如浏览器型号及版本、操作系统、出 Bug 时按 F12 打开 devtools 并切换到 Console 标签页的截图

**Comment by beautifulword** [comment]
![image](https://user-images.githubusercontent.com/35883958/147398325-0ea31d9c-9720-4204-83d0-189718bab23e.png)
随便打开一本漫画阅读模式点击下一话都是如此。
![image](https://user-images.githubusercontent.com/35883958/147398336-0fdcaca7-57f2-4223-97c0-9efd04d17d3f.png)
脚本只留了comicread
![image](https://user-images.githubusercontent.com/35883958/147398355-13bb4411-b135-4a46-9529-8362fd73a394.png)
扩展只留了油猴
![image](https://user-images.githubusercontent.com/35883958/147398380-15623c90-6073-4e14-bca2-6e6d1515e8b9.png)
![image](https://user-images.githubusercontent.com/35883958/147398383-c9eda85b-c595-4908-8eab-f4af95380738.png)
点击下一话前后的截图
![image](https://user-images.githubusercontent.com/35883958/147398402-d61ddece-7a61-41e0-9bff-734fc2384c91.png)
浏览器版本
![image](https://user-images.githubusercontent.com/35883958/147398415-e5d584d4-c29a-4f83-9968-292c36547cc7.png)
win10

**Comment by beautifulword** [comment]
另外这是卷轴模式的bug，非卷轴模式下点击下一话前后
![image](https://user-images.githubusercontent.com/35883958/147398465-62f2e6c8-9bb7-4bbd-8369-d6f521b26ab5.png)
![image](https://user-images.githubusercontent.com/35883958/147398487-548ff5a4-861d-4991-8ad4-2ff1c84ff05d.png)

**Comment by hymbz** [comment]
已修复更新。
完全没想到是卷轴模式的 bug (つд⊂)，那没事了，是以前修改功能时忘了改卷轴模式的代码导致的 bug。

**Comment by beautifulword** [comment]
感谢修复φ(゜▽゜*)♪
