### ISSUE TITLE
卷轴模式下使用空格会直接跳到下一话

### ISSUE THREAD

**Issue by beautifulword** [hymbz/ComicReadScript#49]
但是我还没看完呢😂，并且连按两下上键就跳到上一话对我这种经常上下微调的人来说就难受了，请问开发者能做成上下键就在本话微调，左右键跳到上一话和下一话，空格键翻页这种模式吗?

**Comment by hymbz** [comment]
更新晚了抱歉，已更新修复，现在在卷轴模式下不会再自动跳转到上/下一话了。

**Comment by beautifulword** [comment]
感谢修复
