### ISSUE TITLE
卷軸模式仍會觸發翻頁模式的下一話

### ISSUE THREAD

**Issue by leadra** [hymbz/ComicReadScript#51]
今日在copymanga卷軸模式下，仍然按space或pagedown等翻頁動作數次後會直接跳下一話。
剛剛反覆測試翻頁和卷軸後，發現是因為，即使在卷軸模式下仍會觸發翻頁模式的閱讀進度，造成卷軸在往下跳，實際上會觸發翻頁的最後出現的[上一話 ENd 下一話]
EX:雙頁有8頁，在末頁翻頁後會出現[上一話 ENd 下一話]，然後翻頁按鍵pagedown,space,→  就會執行下一話，而如果在卷軸模式下一樣會執行此項操作，造成還沒看完就跳下一話

令請教，更改哪裡可以設定最大圖片上限呢?
https://copymanga.org/comic/buxingzhiyedexingyun
卷軸下原圖有點大，想要限制最大顯示寬度

**Comment by hymbz** [comment]
更新晚了抱歉，已更新修复，现在在卷轴模式下不会再自动跳转到上/下一话了。

另外关于设置图片宽度，脚本正在重构大改中，因为不想浪费时间在旧版本的修改上，所以还请等待重构后的版本更新。现在就暂且通过直接调整浏览器的宽度来调整吧 |ー`)

**Comment by leadra** [comment]
了解，感謝，期待新版本出現
PS.縮小瀏覽器%百分比圖片不會變，本來是問程式碼哪個位置，不過不重要了，期待新款的載入
