### ISSUE TITLE
怎么才能让右键菜单里不显示脚本呢？

### ISSUE THREAD

**Issue by 7sevenseven** [hymbz/ComicReadScript#53]
如题，右键本来就有点臃肿，不想comicread再占一行了

**Comment by hymbz** [comment]
是说随便一个网页里点击右键弹出的右键菜单吗？请问你用是什么浏览器？哪个油猴扩展？

我是 chrome + Tampermonkey，网页右键菜单里是完全没有相关选项的。脚本也只在油猴扩展的菜单里加了相关的选项。
