### ISSUE TITLE
nhentai.net最近经常抽风，已经使用新的域名nhentai.to请求适配

### ISSUE THREAD

**Issue by JeffCheung85** [hymbz/ComicReadScript#54]
nhentai.net最近经常抽风，已经使用新的域名nhentai.to请求适配

**Comment by hymbz** [comment]
https://www.reddit.com/r/nhentai/comments/p9em37/which_is_the_real_link/

**Comment by JeffCheung85** [comment]
是哦，谷歌搜nhentai第一个就是to，也太厉害了，被骗了

**Comment by hymbz** [comment]
😂我之前也是被骗了 https://greasyfork.org/zh-CN/scripts/374903-comicread/discussions/130474

我印象里以前谷歌搜索还是正常的，不知道山寨站用了什么办法居然被谷歌排到了第一，之后会考虑给脚本加一个山寨站提醒。
