### ISSUE TITLE
装了脚本后打开相应网站只弹出设置弹窗，但窗口没有内容一片空白，而且关不掉

### ISSUE THREAD

**Issue by hoomii11** [hymbz/ComicReadScript#56]

**Comment by hymbz** [comment]
好像是以前出现过的 bug。。
具体是用的什么浏览器？油猴扩展是哪个？打开了哪个网站？

**Comment by zhonghongming** [comment]
我试了edge跟chrome都是这个问题，都是在各自扩展商店下的油猴，也试过用暴力猴，用暴力猴在[GreasyFork]安装的话会显示 加载脚本依赖错误

**Comment by hymbz** [comment]
是 Tampermonkey 没错吧？edge 和 chrome 都是最新版本吗？我这边两个都能正常运行。可能是和其他扩展或脚本产生的冲突？

**Comment by hoomii11** [comment]
对的，Tampermokey，我试了把其它所有脚本都关掉了，还是这样

**Comment by hymbz** [comment]
edge 和 chrome 都是最新版本吗？操作系统是？

**Comment by hoomii11** [comment]
对，浏览器都是最新版，win11

**Comment by hoomii11** [comment]
可能是的，我刚刚用平板上的kiwi试了一下倒是可以正常使用

**Comment by hoomii11** [comment]
可能是的，我刚刚用平板上的kiwi试了一下倒是可以正常使用

**Comment by hymbz** [comment]
是外部资源没有成功加载导致的，具体应该可以点进脚本编辑页，切换到「外部」标签页来看。

我这边只在折腾科学上网导致网络状况不佳时成功复现了一次，之后就都能正常加载。

**Comment by hoomii11** [comment]
现在已经没问题了，多谢
