### ISSUE TITLE
漫画柜好像失效了

### ISSUE THREAD

**Issue by blass0009** [hymbz/ComicReadScript#59]
漫画阅读界面的“阅读模式”按钮还在，但是点了没反应
例如电锯人第99话[https://www.manhuagui.com/comic/30252/644280.html](url)
![image](https://user-images.githubusercontent.com/20455106/180426510-da0139bf-8e9f-4958-ae19-e9d91888cada.png)
也无法自动进入阅读模式

在其他网站试了一下，工作正常，尚未发现失效的

**Comment by JeffCheung85** [comment]
能点，尝试下挂梯子

**Comment by blass0009** [comment]
又正常了……奇怪

**Comment by hymbz** [comment]
好像是因为之前有段时间页面改版导致的，虽然现在没问题但还是参考 [sleazyfork的提议](https://sleazyfork.org/zh-CN/scripts/374903-comicread/discussions/142152) 更新了下代码
