### ISSUE TITLE
可以增加快捷键嘛，能自定义快捷键就最好了

### ISSUE THREAD

**Issue by JeffCheung85** [hymbz/ComicReadScript#60]
希望给页面填充添加快捷键，键盘点着点着发现分页不对要用鼠标去点翻页，如果增加快捷键就优雅多了

**Comment by hymbz** [comment]
好主意！不过因为目前正在 996 中，近期应该是没法更新了|ー`)

**Comment by hymbz** [comment]
自定义快捷键还要画界面，得等之后重构后的大版本更新再上。目前你想用什么按键来切换页面填充？

**Comment by JeffCheung85** [comment]
最接近上下左右的按键就/.,mnb这边吧，M键应该不错

**Comment by hymbz** [comment]
已更新
