### ISSUE TITLE
支持忽略无法下载的图片直接打包下载

### ISSUE THREAD

**Issue by inchei** [hymbz/ComicReadScript#61]
百合会部分漫画会有无关紧要的广告页为失效图片，导致整帖漫画无法打包下载，能否支持忽略无法下载的图片直接打包下载？谢谢。

**Comment by hymbz** [comment]
这里感觉改起来还挺麻烦的，因为脚本目前正在重构中所以非常抱歉没法马上支持，重构后的脚本会支持的。
