### ISSUE TITLE
劳驾问一下能不能切换成美漫的阅读方式

### ISSUE THREAD

**Issue by HYGSWS** [hymbz/ComicReadScript#62]
我在动漫之家看蜘蛛侠，双页模式是从右到左，不太符合美漫的阅读逻辑，请问到哪可以设置？

**Comment by hymbz** [comment]
已更新美漫模式。现在可以在油猴扩展菜单里点击脚本的「漫画阅读脚本设置」弹出设置框，在其中选择启用美漫模式。
