### ISSUE TITLE
动漫之家漫画脚本失效

### ISSUE THREAD

**Issue by heptaspirit** [hymbz/ComicReadScript#67]
应该是最近的网站更新，现在脚本对动漫之家已经完全失效，强行打开脚本也只会加载一页（初始的一页）

另外建议在脚本的`home-url`里把github项目的网页也加上

**Comment by hymbz** [comment]
是因为动漫之家又把域名换成 idmzj.com 了导致的，之前也有过是技术性调整之后还会换回来的。

然后非常抱歉因为一些原因现在暂时不方便更新脚本，不介意的话可以先用测试版顶一顶 ——https://github.com/hymbz/ComicReadScriptTest/raw/master/ComicRead.user.js

**Comment by heptaspirit** [comment]
dmzj已经恢复原先域名了，脚本又能正常使用
