### ISSUE TITLE
动漫之家隐藏漫画显示问题

### ISSUE THREAD

**Issue by p88q** [hymbz/ComicReadScript#68]
动漫之家部分漫画无法显示，例如：《勇者死了！是因为勇者掉进了作为村民的我挖的陷阱里》
但是https://greasyfork.org/zh-CN/scripts/466729-%E5%8A%A8%E6%BC%AB%E4%B9%8B%E5%AE%B6%E8%A7%A3%E9%99%A4%E5%B1%8F%E8%94%BD
这个插件可以显示。能不能更新一下

**Comment by hymbz** [comment]
因为一些原因现在暂时不方便更新脚本，不介意的话可以先用测试版顶一顶 ——https://github.com/hymbz/ComicReadScriptTest/raw/master/ComicRead.user.js
