### ISSUE TITLE
全局脚本会影响某些网站功能（last.fm）

### ISSUE THREAD

**Issue by fireattack** [hymbz/ComicReadScript#7]
要重现首先得有个last.fm的账号并且有播放记录。所以不知道作者是否方便。

然后，在个人主页对任何歌曲点“喜欢”（心），会发送一个XHR请求 `POST "https://www.last.fm/user/[你的用户名]/loved"`。但是开启此脚本之后，这个请求会失效的感觉（虽然无报错），导致无法标记喜欢成功。

不知道是不是作者的实现方式的关系，其实这不是我碰到的第一个和Ajax有关的bug了，感觉在YouTube也有冲突（会导致字幕（CC）按钮失效），但是那个我还没有仔细验证。

**Comment by fireattack** [comment]
范例图

![image](https://user-images.githubusercontent.com/4130991/49779046-e5610180-fcff-11e8-940c-f90401473f7b.png)

**Comment by hymbz** [comment]
emm，我在 last.fm 注册了账号，但不知道是什么问题，我在进入个人主页后控制台就报了一大堆错，即使我禁用了油猴扩展也是。个人主页里我连心都点不了，但其他页面就没问题。Chrome、Firefox、Edge都是这样(´_ゝ`)。

所以没办法，你在脚本头部注释里加上一行`// @exclude     http*last.fm*`，让脚本不在 last.fm 启用吧。或者加上
```
// @include     *bbs.yamibo.com*
// @include     *www.yamibo.com*
// @include     *i.dmzj.com*
// @include     *m.dmzj.com*
// @include     *manhua.dmzj.com*
// @include     *exhentai.org*
// @include     *e-hentai.org*
// @include     *nhentai.net*
```
让脚本只在支持站点启用。

为了防止脚本冲突我特意封装了主要内容，在支持站点以外的网站，脚本除了声明变量函数外只往 Tampermonkey 扩展菜单里加了一个选项。应该只有点击选项后脚本才会影响到网页才对。。。

**Comment by fireattack** [comment]
我又测试了下几发，发现这个问题确实比我想象的奇怪…我重新启用comicRead然后禁用另外一个脚本，似乎也能修复bug

感觉可能是tempermonkey处理多个脚本的时候的冲突问题（外加last.fm写得差）。

总之多谢了。
