### ISSUE TITLE
DM5頁面無法和視窗大小相符

### ISSUE THREAD

**Issue by s94039403** [hymbz/ComicReadScript#72]
![image](https://github.com/hymbz/ComicReadScript/assets/53208472/051b6e83-8403-4f26-b1d3-4cfc7bad6d57)
按填充頁面也沒辦法把圖片拉寬放大
三天前還正常
似乎是更新過後出問題

**Comment by s94039403** [comment]
![image](https://github.com/hymbz/ComicReadScript/assets/53208472/52e7148f-63fb-42a1-b689-1b1f80b9928d)

剛才嘗試從6.0退到5.5版本
就正常了 圖片會自動適應瀏覽器本身寬度
回報給作者 感謝作者辛勞!

**Comment by hymbz** [comment]
新版已更新，现在默认宽度是和显示高度一致，并且可以用 alt + 滚轮 的缩放来调整

因为平时比较少用卷轴模式条漫也比较少看的缘故，所以没想到这个宽度会太小😂

6.0之前的版本没记错的话，是不对图片宽度做任何限制和原图一致的，好奇问下你平时都是像第二张截图这样看的吗

**Comment by s94039403** [comment]
感謝作者幫忙解決問題
是的我平常都是像第二張截圖這樣
我個人習慣是卷軸模式 用滑鼠滾輪往下
因為這樣以一般螢幕橫向放置來說圖片可以放夠大 
不會因為硬要單頁或雙頁把圖片縮小
文字閱讀比較舒適
再次感謝
