### ISSUE TITLE
进入e绅士里站的具体漫画页面会自动开始加载漫画

### ISSUE THREAD

**Issue by theseventhman** [hymbz/ComicReadScript#73]
打开e绅士里站的具体的漫画页面后会自动开始加载漫画，之前都是要手动点击load才会加载漫画的
而且切换到卷轴模式的时候的画面和以前相比也变小了，是因为更新到6.0版本的问题吗？

**Comment by hymbz** [comment]
可以在右下角悬浮按钮的菜单里关掉自动进入阅读模式的功能。卷轴模式则是可以通过 alt+滚轮 来调整宽度。

我不常用卷轴模式，之前图片是直接显示出来不做任何处理的，后来开始追一部条漫才开始改卷轴模式相关功能，因为感觉直接显示太大了所以限制了图片宽度。

默认就是图片的原始尺寸会更好吗？

**Comment by theseventhman** [comment]
我个人还是比较习惯在卷轴模式下观看漫画的，因为之前的版本在卷轴模式下，图片的尺寸会放大，眼睛观看的时候没那么累

试了下，升级到6.0.1版本就没问题了，卷轴模式下图片的尺寸大小也变大了， 感谢回复
