### ISSUE TITLE
动漫之家_在非[漫画阅读模式]下，漫画页阅读跳进定位不合理问题报告

### ISSUE THREAD

**Issue by DOOMxKID** [hymbz/ComicReadScript#74]
Hi,
首先我无法验证这是不是我独有的问题，如果是，请忽略issue。
现象描述：
在动漫之家站点不使用阅读模式，进入漫画单话阅读后，单击漫画页page1跳转至下一页page2，发现跳转的位置会导致顶部的信息框盖住page2上方大约200个像素。
具体现象可以看附件：
![Snipaste_2023-07-01_13-17-44](https://github.com/hymbz/ComicReadScript/assets/116968227/721cdc6d-d10e-4a0c-aa2e-b23ccf29603c)

**Comment by hymbz** [comment]
主要是因为之前样式美化会把顶栏固定显示导致的，已经更新了新版删掉了样式美化功能
