### ISSUE TITLE
在已支持的站点开启简易阅读模式后没有关闭按钮,无法退出

### ISSUE THREAD

**Issue by 4thNeko** [hymbz/ComicReadScript#79]
在已支持的站点开启简易阅读模式,刷新后右下角提示获取漫画图片失败,无视提示点击进入阅读模式后会从阅读页面闪退到原页面.
无法通过从[#简易阅读模式](https://github.com/hymbz/ComicReadScript#%E7%AE%80%E6%98%93%E9%98%85%E8%AF%BB%E6%A8%A1%E5%BC%8F)中提示的右下角悬浮按钮中的快捷按钮关闭(因为没有关闭按钮),
在脚本储存页面将参数 清空 或将对应站点的 `"记住当前站点": true`改为 `false`后恢复.
此外还发现与Dark Reader拓展有冲突,在同时开启后进入阅读页面,背景变为透明且不显示滚动条.

**Comment by hymbz** [comment]
正常在已支持的站点是不应该显示简易阅读模式的菜单项的，这个是我前几天重构的时候忘记加判断了。。已经更新修复了。

Dark Reader 其实我也在用，我是选择在常用的漫画站上直接禁用 Dark Reader。因为之前找不到办法解决，Dark Reader 的动态模式太猛了。
不过你刚才提到以后我又重新试了一下，这次倒是找到办法了，就是改动有点大。虽然目前我测试没问题，但可能只是我没测到，如果有无法解决的冲突 bug，或是之后也可能会因为和想加的优先级更高的新功能发生冲突的话，那还是会改回来，还请见谅。

**Comment by hymbz** [comment]
这是修改 eh 加载策略留下的 bug。加了快捷键以后我都是直接用快捷键进阅读模式的，结果就把这个漏了。。

会在下次更新修掉。
