### ISSUE TITLE
DMZJ里封禁的漫画使用脚本后丢失"站内短消息订阅"跟"RSS订阅"按钮

### ISSUE THREAD

**Issue by shinji-ikari** [hymbz/ComicReadScript#8]
浏览器：firefox 52
插件：Tempermonkey
脚本版本：应该刚更新的。
问题：DMZJ的封禁漫画能正常看到话数，但是话数右上角的RSS订阅跟短消息订阅按钮丢失。

**辛苦大大维护更新脚本。(,,´•ω•)ノ"(´っω•｀。)

![1](https://user-images.githubusercontent.com/12407493/50559052-1bf1d100-0d2e-11e9-8267-d5f22b2960b6.png)

**Comment by hymbz** [comment]
回复晚了抱歉。被封漫画用不了RSS订阅，应该是动漫之家禁的。站内信息订阅其实就是订阅，直接点漫画封面下的订阅按钮就可以了。所以这两个按钮其实都是多余的，没必要做。

**Comment by shinji-ikari** [comment]
明白了.感谢解答
