### ISSUE TITLE
[Feature Request]添加在百合會帖子第一頁以外開啟閱讀模式的按鈕

### ISSUE THREAD

**Issue by p4ssen** [hymbz/ComicReadScript#82]
以[百合會][平尾アウリ] まんがの作り方(漫畫的製作方法) 第6卷（42-46話）
https://bbs.yamibo.com/forum.php?mod=viewthread&tid=209541&fromuid=341039
為例，樓主將圖片發在不同樓以至於帖子超出一頁。

**Comment by hymbz** [comment]
已更新，现在后面几页也会显示按钮了。

十分感谢你的反馈，让我知道现在还有人在用这个脚本看300😭。~~这个脚本发布以来300的反馈屈指可数，300上的发布贴也没什么人回复，每次改300相关的代码都在怀疑除了我以外真的还有300人在用吗？~~
