### ISSUE TITLE
ComicRead PWA 在安卓上无法选择文件

### ISSUE THREAD

**Issue by Vigilans** [hymbz/ComicReadScript#83]
在安卓（MIUI 14）的以下环境下：
* Chrome 浏览器
* Kiwi 浏览器
* 使用 Chrome 浏览器安装的 PWA 应用

无论是否使用桌面版网站，点“选择文件”与“选择文件夹”均无反应。

**Comment by hymbz** [comment]
更新支持了。

不过我是不太推荐在手机上用这个看漫画的，毕竟终究只是网页，受手机端浏览器的限制，只能选择文件没法直接选文件夹。而且 ComicRead 的主要功能还是双页+页面填充，而这两点在手机上都发挥不出来。手机上的漫画 app 数量又多质量又高，相比之下 ComicRead PWA 就是个残疾人。

不过如果你确实想用，也欢迎你说说自己的使用场景和建议，只要不是非常难实现的话我还是会实装上去的。

**Comment by Vigilans** [comment]
确实，试用了一下更新后的版本，安卓的机制似乎不方便选择文件夹，这样的话就满足不了需求了。

我的需求并不是拿来看漫画，而是在安卓里方便快速地使用[manga-image-translator](https://github.com/zyddnys/manga-image-translator/blob/main/README_CN.md)。如果用Web网页的话，切换应用一张张上传图很累，如果能直接在某个应用里边看漫画边翻译就方便多了，所以就尝试了ComicRead PWA。

围绕manga-image-translator的安卓生态确实少（或者根本找不到……），也许得考虑自己糊个玩具app出来了……我觉得比较好的方案是：
* 分享一张图片给这个app，这个app会调用manga-image-translator显示翻译后图片。这种功能的应用我知道有Naver Papago，但是漫画翻译质量实在不敢恭维。而且能用自己本地部署的manga-image-translator是最好的。
* 通过某种开关（如双指长按屏幕，或是通知下拉快捷开关），截图当前页面，使用manga-image-translator翻译后原地绘制在当前屏幕上。这个是很多安卓桌面有的功能（比如emui智慧识屏），但是翻译漫画的质量也不咋样。这个功能github有人做了个原型出来：https://github.com/vamsi3/screen-translator，截图后分享给papago或google lens从而在当前屏幕上翻译。

**Comment by hymbz** [comment]
原来如此，那我这边确实是无能为力了。。
