### ISSUE TITLE
匹配ehentai的多页查看器

### ISSUE THREAD

**Issue by lilyblessing** [hymbz/ComicReadScript#86]
普通画廊地址：https://exhentai.org/g/***/***/
多页查看器地址：https://exhentai.org/mpv/***/***/

多页查看器需要在Hath Perks页面启用

**Comment by hymbz** [comment]
已更新支持。

不过我 Hath 不够没法开启，现在是照着 [演示页](https://e-hentai.org/mpv/530350/8b3c7e4a21/) 做的适配，你看下能正常使用吗？

**Comment by lilyblessing** [comment]
正常使用，感谢支持适配
