### ISSUE TITLE
[Question] would you like to support kemono.party officially by you reader?

### ISSUE THREAD

**Issue by EnergoStalin** [hymbz/ComicReadScript#87]
## Current problem
It's already supported by generic reader as i can see but it rely on fanbox servers for downloading which obviously wont work unless you supply credentials in request.

## Possible karma damage
Supporting site leakers always not good to karma but as i can see e-hentai well supported which also has leaks not as the main part but still. So avoiding support will be completely understandable.

## Why people might want this
Let's only say what i currently live in Russia and use kemono.party quite often not bringing the whole bunch of political and usability issues accessing foreign paid content.

## Why in english
I decided to write that in english cause i cant be responsible for translator mistakes, it would be helpful for others who read too and it's simply community standard. English also not my native language tho.

## English -> Russian
I wish to help localizing that project so ping me out when english translation will be done and you will get Russian right away.

**Comment by EnergoStalin** [comment]
I was able to trick it by using another userscript like this to preprocess images with original size links first now it load images perfectly and translations finally working. Not sure why it tried to download full images from downloads.fanbox.cc initially tho

```js
const links = Array.from(document.querySelectorAll("div.post__thumbnail > a:nth-child(1)"));
for(const link of links) {
  const img = link.querySelector("img");
  img.removeAttribute("loading");
  img.setAttribute("data-src", link.href);
  console.log(img);
}
```

**Comment by hymbz** [comment]
## kemono.party

Already updated to support kemono.party.

Thank you, if it weren't for your reminder, I wouldn't have known that kemono.party can display the original size😂. I have been using the general reading mode to read directly before.

## i18n

Thank you very much for being willing to help with the translation!

The script has already implemented i18n, and now you can translate it through [Weblate](https://hosted.weblate.org/engage/comic_read_script/).~~This is actually my first time getting the chance to use Weblate.~~

But my English level is very poor, and the English translation now is done with the help of ChatGPT. There will definitely be grammar errors in it, so if you find any grammar mistakes, feel free to correct them.

Thank you once again for your kind assistance!!!

---

## kemono.party

已更新支持 kemono.party。

感谢，如果不是你提醒了我，我都不知道 kemono.party 可以显示原始尺寸😂。我之前一直在用通用阅读模式直接阅读。

## i18n

非常感谢你愿意帮忙翻译！脚本已经实现了 i18n，你现在可以通过 [Weblate](https://hosted.weblate.org/engage/comic_read_script/) 进行翻译。~~这还是我第一次有机会用上 Weblate~~

但我的英文水平很差，现在的英文翻译是借助 ChatGPT 翻译的，其中肯定会有语法错误，如果你发现了语法错误可以直接改掉。

最后，再次感谢你！！！

**Comment by EnergoStalin** [comment]
Great!

Translation also done
