### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by zouhai44** [hymbz/ComicReadScript#95]
2台电脑 一台部署了翻译 在本地可以实现翻译 
另一台电脑 改url   会出现加载出错 。 docker 后台会有数据显示 证明翻译出错
本地的没有的事

**Comment by zouhai44** [comment]
另一台电脑改url会出现加载错误。docker后台有数据显示翻译成功 但是加载出错

**Comment by hymbz** [comment]
是因为什么才需要改 url？F12 的控制台里有报错信息吗？

**Comment by hymbz** [comment]
另外，直接用 manga-image-translator 的 web ui 翻译可以正常显示吗？

**Comment by zouhai44** [comment]
目的:我有个云电脑 我想用他来搭个翻译服务 不想在本机用
用manga-image-translator  可以 实现翻译 本地 和 另一台机子都可以 
但是用 ComicReadScript 用你的方法 本地部署的可以用 但是 另一台机子修改url 会显示加载出错

**Comment by zouhai44** [comment]
![image](https://github.com/hymbz/ComicReadScript/assets/71769040/1d3d2ba0-e400-4ec6-88be-e47483fdd29f)
![image](https://github.com/hymbz/ComicReadScript/assets/71769040/0415983b-1ec8-4c1f-992f-9d1779b2e6ba)
本地事可以的 （云电脑）
![image](https://github.com/hymbz/ComicReadScript/assets/71769040/754f36eb-be1d-4601-b123-c3513bf12d86)
![image](https://github.com/hymbz/ComicReadScript/assets/71769040/78668730-317f-4f0a-ad30-4a5a2d88ca1f)
![image](https://github.com/hymbz/ComicReadScript/assets/71769040/95dd690f-82f8-4739-946d-191eb05bd8b4)
![image](https://github.com/hymbz/ComicReadScript/assets/71769040/556f9aa6-9255-4989-b583-751a95515c7a)

这是另一台电脑

**Comment by zouhai44** [comment]
![image](https://github.com/hymbz/ComicReadScript/assets/71769040/6c522875-c2c2-4ea7-a026-e8168ae93e00)

**Comment by hymbz** [comment]
感谢截图，知道问题所在了。是因为图片直接用了 manga-image-translator 提供的图片 url，结果触发了 cors。

这是哪个网站？我看下我这边能否复现。

**Comment by zouhai44** [comment]
本地部署的可以实现 翻译 用局域网的另一台不行 
我试过了[k](https://www.1kkk.com/ch1-1395932/) 网站不行 和 e站这个也不行

**Comment by hymbz** [comment]
已更新修复

**Comment by zouhai44** [comment]
我试下 谢谢 大佬··

**Comment by hymbz** [comment]
@EnergoStalin 

> So i wonder is request modifier or custom header needed feature or not.

I think it's not necessary, but I can't be sure. Because of the translation, I can't quite understand what you mean.

Perhaps you can take a look at my code implementation? [selfhosted.ts](https://github.com/hymbz/ComicReadScript/blob/126a76afde7f61561c2953858bdaad03834abc4d/src/components/Manga/hooks/useStore/slice/Translation/selfhosted.ts)

**Comment by EnergoStalin** [comment]
> I think it's not necessary

Same. It's mostly just fun fact. Not actual feature description or request. The speed of colab & localtunnel solution sucks like i said earlier cause either google or localtunnel significantly throttle traffic on top of that you always have random url with localtunnel on each start.
