### ISSUE TITLE
回報BUG 在manhuagui(漫畫櫃)無效

### ISSUE THREAD

**Issue by darron1220** [hymbz/ComicReadScript#98]
![image (2)](https://github.com/hymbz/ComicReadScript/assets/67164842/12c09f90-9b6d-4ed7-9e27-38705380280e)

**Comment by hymbz** [comment]
已更新修复。

改到了打包相关的代码，虽然在打包测试版时没问题，但正式版就会出错。偷懒没测正式版导致了bug上线🙃

**Comment by darron1220** [comment]
問題解決 感謝
