### ISSUE TITLE
A weird issue when using youtube

### ISSUE THREAD

**Issue by markwu** [hymbz/ComicReadScript#99]
When I upgraded the script to ComicRead 7.0, I noticed that the YouTube player icon became very small.

![chrome_2023-09-26_09-31-13](https://github.com/hymbz/ComicReadScript/assets/196861/414ed6f2-4b6a-4d79-8cd7-05c26fd165b5)

After disabling this script or downgrading to 6.10, everything returned to normal.

![chrome_2023-09-26_09-31-30](https://github.com/hymbz/ComicReadScript/assets/196861/0215035a-723e-4f8a-990f-380e8945ef01)

I suspect it's a bug originating from ComicRead. I'm wondering if you have the time to investigate it.

**Comment by markwu** [comment]
In fact, I don't use this script for YouTube, I just enabled at all times.

**Comment by hymbz** [comment]
Yes, this is the bug of ComicRead. #97

Please update to the latest version to fix it.
